#include "DebuggerWidget.h"
#include <QtWidgets>
DebuggerWidget::DebuggerWidget(QWidget*parent):QWidget(parent),m_process(new QProcess(this)){
    auto*root=new QVBoxLayout(this);root->setContentsMargins(4,4,4,4);auto*bar=new QHBoxLayout;
    auto*cont=new QPushButton("Continue");auto*pause=new QPushButton("Interrupt");auto*step=new QPushButton("Step");auto*next=new QPushButton("Next");auto*refresh=new QPushButton("Refresh Views");m_status=new QLabel("Stopped");for(auto*w:{cont,pause,step,next,refresh})bar->addWidget(w);bar->addStretch();bar->addWidget(m_status);root->addLayout(bar);
    auto*tabs=new QTabWidget; m_output=new QPlainTextEdit;m_output->setReadOnly(true);m_locals=new QPlainTextEdit;m_locals->setReadOnly(true);m_stack=new QPlainTextEdit;m_stack->setReadOnly(true);m_registers=new QPlainTextEdit;m_registers->setReadOnly(true);m_memory=new QPlainTextEdit;m_memory->setReadOnly(true);m_watches=new QListWidget;
    tabs->addTab(m_output,"Console");tabs->addTab(m_locals,"Locals");tabs->addTab(m_stack,"Call Stack");tabs->addTab(m_registers,"Registers");tabs->addTab(m_memory,"Memory");tabs->addTab(m_watches,"Watches");root->addWidget(tabs,1);
    auto*watchRow=new QHBoxLayout;m_watchInput=new QLineEdit;m_watchInput->setPlaceholderText("Watch expression");auto*addWatch=new QPushButton("Add Watch");watchRow->addWidget(m_watchInput,1);watchRow->addWidget(addWatch);root->addLayout(watchRow);
    auto*cmdRow=new QHBoxLayout;m_command=new QLineEdit;m_command->setPlaceholderText("Raw GDB command...");auto*send=new QPushButton("Send");cmdRow->addWidget(m_command,1);cmdRow->addWidget(send);root->addLayout(cmdRow);
    connect(cont,&QPushButton::clicked,this,[this]{sendCommand("continue");});connect(pause,&QPushButton::clicked,this,[this]{if(isRunning())m_process->write("\003",1);});connect(step,&QPushButton::clicked,this,[this]{sendCommand("step");});connect(next,&QPushButton::clicked,this,[this]{sendCommand("next");});connect(refresh,&QPushButton::clicked,this,[this]{refreshPane("info locals",m_locals);refreshPane("bt",m_stack);refreshPane("info registers",m_registers);});connect(send,&QPushButton::clicked,this,[this]{sendCommand(m_command->text());m_command->clear();});connect(m_command,&QLineEdit::returnPressed,send,&QPushButton::click);
    connect(addWatch,&QPushButton::clicked,this,[this]{QString e=m_watchInput->text().trimmed();if(e.isEmpty())return;auto*i=new QListWidgetItem(e+" = …");i->setData(Qt::UserRole,e);m_watches->addItem(i);sendCommand("print "+e);m_watchInput->clear();});connect(m_watches,&QListWidget::itemDoubleClicked,this,[this](QListWidgetItem*i){if(i)sendCommand("print "+i->data(Qt::UserRole).toString());});
    connect(m_process,&QProcess::readyReadStandardOutput,this,[this]{consumeOutput(QString::fromLocal8Bit(m_process->readAllStandardOutput()));});connect(m_process,&QProcess::readyReadStandardError,this,[this]{consumeOutput(QString::fromLocal8Bit(m_process->readAllStandardError()));});connect(m_process,qOverload<int,QProcess::ExitStatus>(&QProcess::finished),this,[this](int,QProcess::ExitStatus){m_status->setText("Stopped");});
}
void DebuggerWidget::consumeOutput(const QString&t){m_output->appendPlainText(t);if(m_capture)m_capture->appendPlainText(t);}
bool DebuggerWidget::startDebugger(const QString&exe,const QString&elf,const QString&wd){if(isRunning())return true;m_process->setWorkingDirectory(wd);m_process->setProcessChannelMode(QProcess::SeparateChannels);QStringList a={"--quiet"};if(!elf.isEmpty())a<<elf;m_output->appendPlainText("> "+exe+" "+a.join(' '));m_process->start(exe,a);if(!m_process->waitForStarted(3000))return false;m_status->setText("Running");sendCommand("set pagination off");return true;}
void DebuggerWidget::stopDebugger(){if(!isRunning())return;sendCommand("quit");if(!m_process->waitForFinished(700)){m_process->terminate();if(!m_process->waitForFinished(700))m_process->kill();}}
bool DebuggerWidget::isRunning()const{return m_process->state()!=QProcess::NotRunning;}
void DebuggerWidget::sendCommand(const QString&c){if(!isRunning()||c.trimmed().isEmpty())return;m_output->appendPlainText("(gdb) "+c);m_process->write((c+"\n").toLocal8Bit());}
void DebuggerWidget::toggleBreakpoint(const QString&file,int line,bool enabled){if(!isRunning())return;QString loc=QString("\"%1\":%2").arg(file).arg(line);sendCommand((enabled?"break ":"clear ")+loc);}
void DebuggerWidget::refreshPane(const QString&cmd,QPlainTextEdit*t){if(!isRunning())return;t->clear();m_capture=t;sendCommand(cmd);QTimer::singleShot(250,this,[this]{m_capture=nullptr;});}
