#include "GameView.h"
#include "SceneDocument.h"
#include <QPainter>
#include <QKeyEvent>
#include <QFileInfo>
#include <QImage>
#include <QElapsedTimer>
#include <QtMath>
#include <cmath>

static bool overlap2D(const QVector3D&a,const SceneObject&A,const QVector3D&b,const SceneObject&B){float ax=a.x()-A.colliderSize.x()/2,ay=a.y()-A.colliderSize.y()/2,bx=b.x()-B.colliderSize.x()/2,by=b.y()-B.colliderSize.y()/2;return ax<bx+B.colliderSize.x()&&ax+A.colliderSize.x()>bx&&ay<by+B.colliderSize.y()&&ay+A.colliderSize.y()>by;}
GameView::GameView(QWidget*p):QWidget(p){setFocusPolicy(Qt::StrongFocus);setMinimumSize(640,448);m_timer.setInterval(16);connect(&m_timer,&QTimer::timeout,this,&GameView::tick);}
void GameView::setDocument(SceneDocument*d){m_doc=d;if(d)connect(d,&SceneDocument::changed,this,qOverload<>(&GameView::update),Qt::UniqueConnection);update();}
void GameView::setProjectRoot(const QString&r){m_root=r;update();}
void GameView::play(){if(!m_doc)return;if(m_playing&&m_paused){m_paused=false;m_timer.start();emit pauseStateChanged(false);return;}if(m_playing)return;m_positions.clear();m_velocities.clear();for(const auto&o:m_doc->objects()){m_positions[o.id]=o.position;m_velocities[o.id]=o.velocity;}m_time=0;m_uiSelection=0;m_playing=true;m_paused=false;m_timer.start();setFocus();emit playStateChanged(true);emit pauseStateChanged(false);update();}
void GameView::pause(){if(!m_playing)return;m_paused=!m_paused;if(m_paused)m_timer.stop();else m_timer.start();emit pauseStateChanged(m_paused);update();}
void GameView::stop(){if(!m_playing)return;m_timer.stop();m_playing=false;m_paused=false;m_positions.clear();m_velocities.clear();m_keys.clear();emit playStateChanged(false);emit pauseStateChanged(false);update();}
void GameView::frameStep(){if(!m_playing){play();pause();}if(!m_paused)pause();advance(1.0f/60.0f);emit frameAdvanced(1000.0f/60.0f);update();}
void GameView::setVideoPreset(const QString&preset){m_videoPreset=preset;if(preset.startsWith("PAL"))m_virtualResolution=QSize(640,512);else if(preset.contains("512x448"))m_virtualResolution=QSize(512,448);else m_virtualResolution=QSize(640,448);update();}
void GameView::advance(float dt){if(!m_doc||!m_playing)return;m_time+=dt;const auto&objs=m_doc->objects();
    for(const auto&o:objs){auto p=m_positions.value(o.id,o.position);auto v=m_velocities.value(o.id,o.velocity);if(!o.tag.compare("Player",Qt::CaseInsensitive)){float speed=180.0f;if(m_keys.contains(Qt::Key_Left))v.setX(-speed);else if(m_keys.contains(Qt::Key_Right))v.setX(speed);else if(o.kinematic)v.setX(0);if(m_keys.contains(Qt::Key_Up))v.setY(-speed);else if(m_keys.contains(Qt::Key_Down))v.setY(speed);else if(o.kinematic)v.setY(0);}if(o.rigidBody&&!o.kinematic&&o.useGravity)v.setY(v.y()+420.0f*o.gravityScale*dt);if(o.rigidBody||o.kinematic)p+=v*dt;m_positions[o.id]=p;m_velocities[o.id]=v;}
    for(int i=0;i<objs.size();++i)for(int j=i+1;j<objs.size();++j){const auto&A=objs[i];const auto&B=objs[j];if(!A.colliderEnabled||!B.colliderEnabled)continue;if(!(A.collisionMask&B.collisionLayer)||!(B.collisionMask&A.collisionLayer))continue;auto a=m_positions.value(A.id,A.position),b=m_positions.value(B.id,B.position);if(!overlap2D(a,A,b,B)||A.trigger||B.trigger)continue;float dx=b.x()-a.x(),dy=b.y()-a.y(),px=(A.colliderSize.x()+B.colliderSize.x())*.5f-qAbs(dx),py=(A.colliderSize.y()+B.colliderSize.y())*.5f-qAbs(dy);bool ad=A.rigidBody&&!A.kinematic,bd=B.rigidBody&&!B.kinematic;if(px<py){float n=dx>=0?-1.0f:1.0f;if(ad)a.setX(a.x()+n*px*(bd?.5f:1));if(bd)b.setX(b.x()-n*px*(ad?.5f:1));auto av=m_velocities[A.id],bv=m_velocities[B.id];if(ad)av.setX(-av.x()*A.restitution);if(bd)bv.setX(-bv.x()*B.restitution);m_velocities[A.id]=av;m_velocities[B.id]=bv;}else{float n=dy>=0?-1.0f:1.0f;if(ad)a.setY(a.y()+n*py*(bd?.5f:1));if(bd)b.setY(b.y()-n*py*(ad?.5f:1));auto av=m_velocities[A.id],bv=m_velocities[B.id];if(ad)av.setY(-av.y()*A.restitution);if(bd)bv.setY(-bv.y()*B.restitution);m_velocities[A.id]=av;m_velocities[B.id]=bv;}m_positions[A.id]=a;m_positions[B.id]=b;}
}
void GameView::tick(){if(!m_doc||!m_playing||m_paused)return;QElapsedTimer t;t.start();advance(1.0f/60.0f);emit frameAdvanced(float(t.nsecsElapsed()/1000000.0));update();}
void GameView::keyPressEvent(QKeyEvent*e){if(!e->isAutoRepeat())m_keys.insert(e->key());if(e->key()==Qt::Key_Up||e->key()==Qt::Key_Down){QList<int>buttons;if(m_doc){for(int i=0;i<m_doc->objects().size();++i)if(m_doc->objects()[i].uiSelectable)buttons<<i;}if(!buttons.isEmpty())m_uiSelection=(m_uiSelection+(e->key()==Qt::Key_Down?1:-1)+buttons.size())%buttons.size();}QWidget::keyPressEvent(e);}
void GameView::keyReleaseEvent(QKeyEvent*e){if(!e->isAutoRepeat())m_keys.remove(e->key());QWidget::keyReleaseEvent(e);}
void GameView::paintEvent(QPaintEvent*){QPainter p(this);p.fillRect(rect(),QColor(10,14,22));p.setRenderHint(QPainter::Antialiasing);double sx=width()/double(m_virtualResolution.width()),sy=height()/double(m_virtualResolution.height());p.save();p.scale(sx,sy);p.setPen(QColor(35,43,58));for(int x=0;x<=m_virtualResolution.width();x+=32)p.drawLine(x,0,x,m_virtualResolution.height());for(int y=0;y<=m_virtualResolution.height();y+=32)p.drawLine(0,y,m_virtualResolution.width(),y);if(!m_doc){p.restore();return;}int selectableSeen=0;
    for(const auto&o:m_doc->objects()){QVector3D pos=m_playing?m_positions.value(o.id,o.position):o.position;QColor tint=QColor::fromRgbF(qBound(0.f,o.materialTint.x(),1.f),qBound(0.f,o.materialTint.y(),1.f),qBound(0.f,o.materialTint.z(),1.f),qBound(0.f,o.materialAlpha,1.f));
        if(o.type=="Sprite"||o.type=="Image"){QString ap=o.asset;if(!QFileInfo(ap).isAbsolute())ap=m_root+"/assets/textures/"+QFileInfo(ap).fileName();QImage im(ap);QRectF r(pos.x(),pos.y(),qMax(16.0f,im.isNull()?48.0f:float(im.width())*o.scale.x()),qMax(16.0f,im.isNull()?48.0f:float(im.height())*o.scale.y()));if(!im.isNull()){p.setOpacity(o.materialAlpha);p.drawImage(r,im);p.setOpacity(1);}else{p.fillRect(r,tint);p.setPen(Qt::white);p.drawText(r,Qt::AlignCenter,o.name);}}
        else if(o.type=="Mesh"){QPointF c(m_virtualResolution.width()/2+pos.x()*35,m_virtualResolution.height()/2-pos.y()*35);double rr=28*qMax(0.25f,o.scale.x());p.setBrush(tint);p.setPen(QColor(190,225,255));QPolygonF poly;for(int i=0;i<6;i++){double a=(i/6.0)*6.28318+m_time*0.2;poly<<QPointF(c.x()+qCos(a)*rr,c.y()+qSin(a)*rr);}p.drawPolygon(poly);}
        else if(o.type=="Panel"||o.type=="Button"){QColor c=QColor::fromRgbF(o.uiColor.x(),o.uiColor.y(),o.uiColor.z(),o.materialAlpha);if(o.uiSelectable){if(selectableSeen==m_uiSelection)c=c.lighter(145);selectableSeen++;}QRectF r(pos.x(),pos.y(),o.uiWidth,o.uiHeight);p.fillRect(r,c);p.setPen(Qt::white);p.drawText(r.adjusted(8,0,-8,0),Qt::AlignVCenter|Qt::AlignLeft,o.uiText.isEmpty()?o.name:o.uiText);}
        if(o.particleEmitter){p.setPen(QColor(255,195,80));for(int i=0;i<qMin(24,o.particleCount);i++){double a=i*.7+m_time*2,d=std::fmod(m_time*60+i*13.0,55.0);p.drawEllipse(QPointF(pos.x()+qCos(a)*d,pos.y()+qSin(a)*d),2,2);}}
        if(o.type=="Text"){p.setPen(QColor::fromRgbF(o.uiColor.x(),o.uiColor.y(),o.uiColor.z()));QFont f=p.font();f.setPixelSize(qMax(10,int(18*o.scale.x())));p.setFont(f);p.drawText(QPointF(pos.x(),pos.y()),o.uiText.isEmpty()?o.name:o.uiText);}
        if(o.colliderEnabled){p.setPen(o.trigger?QColor(255,180,60):QColor(80,230,120));p.setBrush(Qt::NoBrush);p.drawRect(QRectF(pos.x()-o.colliderSize.x()/2,pos.y()-o.colliderSize.y()/2,o.colliderSize.x(),o.colliderSize.y()));}
    }
    p.setPen(m_playing?QColor(100,240,130):QColor(180,190,205));QString state=!m_playing?"STOPPED":(m_paused?"PAUSED":"PLAYING");p.drawText(QPointF(12,22),state+" | "+m_videoPreset+" | component/physics preview; PCSX2/console is authoritative");p.restore();}
