#include "MainWindow.h"
#include "CodeEditor.h"
#include "DebuggerWidget.h"
#include "ClangdClient.h"
#include "ProjectSearchDialog.h"
#include "ProblemsWidget.h"
#include "NewProjectDialog.h"
#include "SceneDocument.h"
#include "SceneView2D.h"
#include "Viewport3D.h"
#include "InspectorWidget.h"
#include "AssetDatabase.h"
#include "AssetCompiler.h"
#include "GameView.h"
#include "ProfilerWidget.h"
#include "RuntimeTemplates.h"
#include "TyraTemplates.h"
#include <QtWidgets>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <functional>
#include <memory>
#include <algorithm>
#include <QSaveFile>
#include <QSettings>
#include "DiscDeployDialog.h"
#include "EnvironmentDoctorDialog.h"
#include "SetupWizardDialog.h"
#include "DependencyManagerDialog.h"
#include "DocumentationDialog.h"
#include "ValidationCenterDialog.h"
#include "UpdateChecker.h"
#include "SupportBundle.h"
#include "SampleProjectGenerator.h"
#include <QTimer>
#include <QFileSystemWatcher>
#include <QRegularExpression>
#include <QDirIterator>
#include <QCloseEvent>
#include <QDesktopServices>
#include <QDateTime>
#include <QMouseEvent>
#include <QTextBlock>
#include <QUrl>

static int entityType(const QString&t){if(t=="Sprite")return 1;if(t=="Mesh")return 2;if(t=="Camera")return 3;if(t=="Light")return 4;if(t=="Text")return 5;if(t=="Panel")return 6;if(t=="Button")return 7;if(t=="Image")return 8;if(t=="AudioSource")return 9;return 0;}
static QString cpp(QString s){s.replace("\\","\\\\");s.replace("\"","\\\"");s.replace("\n","\\n");s.replace("\r","\\r");return "\""+s+"\"";} static QString cstrAsset(const QString&s){return s.isEmpty()?"nullptr":cpp(QFileInfo(s).fileName());} static QString cstrLiteral(const QString&s){return s.isEmpty()?"nullptr":cpp(s);} static QString f32(float v){return QString::number(v,'f',6)+"f";}

MainWindow::MainWindow(QWidget*p):QMainWindow(p),m_process(new QProcess(this)),m_runProcess(new QProcess(this)),m_scene(new SceneDocument(this)),m_assetDb(new AssetDatabase(this)),m_clangd(new ClangdClient(this)){
    buildUi();buildMenus();applyTheme();refreshEnvironment();loadAppState();
    { QSettings st("PS2Studio","PS2Studio"); m_pcsx2Path=st.value("pcsx2Path",m_pcsx2Path).toString(); m_ps2Host=st.value("ps2Host",m_ps2Host).toString(); if(!st.value("setupCompleted",false).toBool()) QTimer::singleShot(0,this,&MainWindow::openSetupWizard); } updateEnvironmentPanel();
    m_autosaveTimer=new QTimer(this);m_autosaveTimer->setInterval(m_autosaveSeconds*1000);connect(m_autosaveTimer,&QTimer::timeout,this,&MainWindow::autosave);m_autosaveTimer->start();
    m_watcher=new QFileSystemWatcher(this);connect(m_watcher,&QFileSystemWatcher::fileChanged,this,&MainWindow::onWatchedPathChanged);connect(m_watcher,&QFileSystemWatcher::directoryChanged,this,&MainWindow::onWatchedPathChanged);
    auto pipe=[this](QProcess*q){connect(q,&QProcess::readyReadStandardOutput,this,[this,q]{appendOutput(QString::fromLocal8Bit(q->readAllStandardOutput()));});connect(q,&QProcess::readyReadStandardError,this,[this,q]{appendOutput(QString::fromLocal8Bit(q->readAllStandardError()));});};pipe(m_process);connect(m_runProcess,&QProcess::readyReadStandardOutput,this,[this]{QString t=QString::fromLocal8Bit(m_runProcess->readAllStandardOutput());appendOutput(t);if(m_profiler)m_profiler->ingestRuntimeOutput(t);});connect(m_runProcess,&QProcess::readyReadStandardError,this,[this]{QString t=QString::fromLocal8Bit(m_runProcess->readAllStandardError());appendOutput(t);if(m_profiler)m_profiler->ingestRuntimeOutput(t);});
    connect(m_process,qOverload<int,QProcess::ExitStatus>(&QProcess::finished),this,[this](int c,QProcess::ExitStatus){appendOutput(QString("\nBuild/tool process finished with code %1\n").arg(c));if(m_runAfterBuild){bool run=(c==0);m_runAfterBuild=false;if(run)runPCSX2();}});
    connect(m_scene,&SceneDocument::changed,this,[this]{m_sceneDirty=true;refreshHierarchy();});connect(m_scene,&SceneDocument::changed,m_profiler,&ProfilerWidget::refresh);connect(m_assetDb,&AssetDatabase::changed,this,&MainWindow::refreshAssets);m_clangd->setDiagnosticsCallback([this](QString file,QList<ClangdDiagnostic> ds){m_diagnostics[file]=ds;QList<PS2StudioProblem> all;for(auto it=m_diagnostics.cbegin();it!=m_diagnostics.cend();++it)for(const auto&d:it.value()){PS2StudioProblem p;p.file=d.file;p.line=d.line;p.column=d.column;p.severity=d.severity;p.message=d.message;p.source=d.source;all<<p;}if(m_problems){m_problems->setProblems(all);if(!all.isEmpty())m_problemsDock->show();}for(int i=0;i<m_editorTabs->count();++i){auto*ed=dynamic_cast<CodeEditor*>(m_editorTabs->widget(i));if(!ed||ed->filePath()!=file)continue;QHash<int,int> lines;for(const auto&d:ds)lines[d.line]=d.severity;ed->setDiagnosticLines(lines);}});
}
void MainWindow::buildUi(){resize(1650,980);setWindowTitle("PS2 Studio 0.18 Tyra Backend");auto*tb=addToolBar("Main");tb->setMovable(false);tb->addAction("New",this,&MainWindow::newProject);tb->addAction("Open",this,&MainWindow::openProject);tb->addSeparator();tb->addAction("+ Object",this,&MainWindow::addSceneObject);tb->addAction("Import",this,&MainWindow::importAsset);tb->addSeparator();tb->addAction("Build",this,&MainWindow::buildProject);tb->addAction("▶ Play",this,&MainWindow::buildAndRun);tb->addAction("■ Stop",this,&MainWindow::stopRun);tb->addAction("PCSX2",this,&MainWindow::runPCSX2);tb->addAction("Real PS2",this,&MainWindow::sendToPS2);m_profileCombo=new QComboBox;m_profileCombo->addItems({"Debug","Optimized","Release"});tb->addSeparator();tb->addWidget(new QLabel(" Profile: "));tb->addWidget(m_profileCombo);m_targetCombo=new QComboBox;m_targetCombo->addItems({"EE / gsKit","EE + experimental VU1","IOP","VU/DVP"});tb->addWidget(new QLabel(" Target: "));tb->addWidget(m_targetCombo);m_videoPresetCombo=new QComboBox;m_videoPresetCombo->addItems({"NTSC 640x448","NTSC 512x448","PAL 640x512"});tb->addWidget(new QLabel(" Video: "));tb->addWidget(m_videoPresetCombo);
    m_workspaceTabs=new QTabWidget;setCentralWidget(m_workspaceTabs);m_scene2D=new SceneView2D;m_scene2D->setDocument(m_scene);m_view3D=new Viewport3D;m_view3D->setDocument(m_scene);m_gameView=new GameView;m_gameView->setDocument(m_scene);connect(m_videoPresetCombo,&QComboBox::currentTextChanged,m_gameView,&GameView::setVideoPreset);m_editorTabs=new QTabWidget;m_editorTabs->setTabsClosable(true);connect(m_editorTabs,&QTabWidget::tabCloseRequested,this,[this](int i){closeEditorTab(i);});m_workspaceTabs->addTab(m_scene2D,"2D Scene");m_workspaceTabs->addTab(m_view3D,"3D Scene");m_workspaceTabs->addTab(m_gameView,"Game View");m_workspaceTabs->addTab(m_editorTabs,"Code");tb->addSeparator();tb->addAction("Pause",m_gameView,&GameView::pause);tb->addAction("Frame",m_gameView,&GameView::frameStep);connect(m_scene2D,&SceneView2D::objectSelected,this,&MainWindow::selectObject);connect(m_scene2D,&SceneView2D::objectMoved,this,[this](const QString&id,double,double){m_selectedObjectId=id;m_inspector->setObjectId(id);refreshHierarchy();});
    auto*pd=new QDockWidget("Project",this);m_projectTree=new QTreeWidget;m_projectTree->setHeaderHidden(true);pd->setWidget(m_projectTree);addDockWidget(Qt::LeftDockWidgetArea,pd);connect(m_projectTree,&QTreeWidget::itemDoubleClicked,this,[this](QTreeWidgetItem*it,int){auto path=it->data(0,Qt::UserRole).toString();if(!QFileInfo(path).isFile())return;if(path.endsWith(".ps2scene")){QString e;if(m_scene->load(path,&e))m_workspaceTabs->setCurrentWidget(m_scene2D);else QMessageBox::warning(this,"Scene",e);}else if(path.endsWith(".ps2prefab")){QString e;if(!m_scene->instantiatePrefab(path,&e))QMessageBox::warning(this,"Prefab",e);}else openFile(path);});
    auto*hd=new QDockWidget("Hierarchy",this);m_hierarchy=new QTreeWidget;m_hierarchy->setHeaderHidden(true);hd->setWidget(m_hierarchy);addDockWidget(Qt::LeftDockWidgetArea,hd);tabifyDockWidget(pd,hd);connect(m_hierarchy,&QTreeWidget::itemSelectionChanged,this,[this]{auto a=m_hierarchy->selectedItems();if(!a.isEmpty())selectObject(a.first()->data(0,Qt::UserRole).toString());});
    auto*id=new QDockWidget("Inspector / Components",this);m_inspector=new InspectorWidget;m_inspector->setDocument(m_scene);id->setWidget(m_inspector);addDockWidget(Qt::RightDockWidgetArea,id);connect(m_inspector,&InspectorWidget::objectEdited,this,[this]{refreshHierarchy();m_scene2D->update();m_view3D->update();m_gameView->update();});
    auto*ad=new QDockWidget("Assets",this);m_assets=new QListWidget;ad->setWidget(m_assets);addDockWidget(Qt::RightDockWidgetArea,ad);connect(m_assets,&QListWidget::itemDoubleClicked,this,[this](QListWidgetItem*i){auto*o=m_scene->objectById(m_selectedObjectId);if(!o)return;QString a=i->text();if(a.startsWith("textures/")){if(o->type=="Mesh")o->materialTexture=QFileInfo(a).fileName();else o->asset=QFileInfo(a).fileName();}else if(a.startsWith("models/"))o->asset=QFileInfo(a).fileName();else if(a.startsWith("audio/"))o->audioAsset=QFileInfo(a).fileName();else if(a.startsWith("animations/"))o->animationAsset=QFileInfo(a).fileName();m_scene->notifyChanged();m_inspector->setObjectId(o->id);});
    auto*prof=new QDockWidget("PS2 Profiler",this);m_profiler=new ProfilerWidget;m_profiler->setDocument(m_scene);connect(m_gameView,&GameView::frameAdvanced,m_profiler,&ProfilerWidget::setFrameTime);prof->setWidget(m_profiler);addDockWidget(Qt::RightDockWidgetArea,prof);tabifyDockWidget(ad,prof);
    auto*bottom=new QDockWidget("Build / Debug Output",this);m_buildOutput=new QPlainTextEdit;m_buildOutput->setReadOnly(true);bottom->setWidget(m_buildOutput);addDockWidget(Qt::BottomDockWidgetArea,bottom);connect(m_buildOutput,&QPlainTextEdit::selectionChanged,this,[this]{if(m_buildOutput->textCursor().hasSelection())return;});m_buildOutput->installEventFilter(this);connect(m_buildOutput,&QPlainTextEdit::cursorPositionChanged,this,[this]{});auto*env=new QDockWidget("PS2 Environment",this);m_envSummary=new QLabel;m_envSummary->setTextInteractionFlags(Qt::TextSelectableByMouse);env->setWidget(m_envSummary);addDockWidget(Qt::BottomDockWidgetArea,env);tabifyDockWidget(bottom,env);m_statusTarget=new QLabel("No project");statusBar()->addPermanentWidget(m_statusTarget,1);m_debugger=new DebuggerWidget; m_debugDock=new QDockWidget("GDB Debugger",this);m_debugDock->setWidget(m_debugger);addDockWidget(Qt::BottomDockWidgetArea,m_debugDock);tabifyDockWidget(bottom,m_debugDock);m_debugDock->hide();m_problems=new ProblemsWidget(this);m_problems->setOpenCallback([this](const QString&f,int line,int col){openFile(f);if(auto*ed=currentEditor())ed->gotoLine(line,col);});m_problemsDock=new QDockWidget("Problems (clangd)",this);m_problemsDock->setWidget(m_problems);addDockWidget(Qt::BottomDockWidgetArea,m_problemsDock);tabifyDockWidget(bottom,m_problemsDock);m_problemsDock->hide();
}
void MainWindow::buildMenus(){
    auto*f=menuBar()->addMenu("File");
    f->addAction("New Project",this,&MainWindow::newProject,QKeySequence::New);f->addAction("Open Project",this,&MainWindow::openProject,QKeySequence::Open);f->addSeparator();
    f->addAction("New C++ Source",this,&MainWindow::newSourceFile,QKeySequence("Ctrl+Shift+N"));f->addAction("New Header",this,&MainWindow::newHeaderFile);f->addAction("New Gameplay Component",this,&MainWindow::newComponent,QKeySequence("Ctrl+Alt+N"));f->addAction("Save",this,&MainWindow::saveCurrent,QKeySequence::Save);f->addAction("Save All",this,[this]{saveAllEditors();},QKeySequence("Ctrl+Shift+S"));f->addAction("Save As...",this,&MainWindow::saveCurrentAs,QKeySequence::SaveAs);f->addAction("Recover Autosave",this,&MainWindow::recoverAutosave);f->addSeparator();f->addAction("Project Settings",this,&MainWindow::configureProject);
    auto*recent=f->addMenu("Recent Projects");for(const auto&p:QSettings("PS2Studio","PS2Studio").value("recentProjects").toStringList()){if(!QFileInfo::exists(p))continue;auto*a=recent->addAction(p);connect(a,&QAction::triggered,this,[this,p]{loadProjectTree(p);m_assetDb->setProjectRoot(p);m_gameView->setProjectRoot(p);m_profiler->setProjectRoot(p);auto cfg=readProjectConfig();m_ps2Host=cfg.value("ps2Host").toString(m_ps2Host);m_pcsx2Path=cfg.value("pcsx2Path").toString();loadDefaultScene();rememberProject(p);updateFileWatchers();updateEnvironmentPanel();});}
    auto*edit=menuBar()->addMenu("Edit");edit->addAction("Find",this,&MainWindow::findInEditor,QKeySequence::Find);edit->addAction("Replace",this,&MainWindow::replaceInEditor,QKeySequence::Replace);edit->addAction("Find in Project",this,&MainWindow::findInProject,QKeySequence("Ctrl+Shift+F"));edit->addAction("Go to Line",this,&MainWindow::gotoLine,QKeySequence("Ctrl+G"));edit->addAction("Go to Definition (clangd)",this,&MainWindow::goToDefinition,QKeySequence("F12"));edit->addAction("Find References (clangd)",this,&MainWindow::findReferences,QKeySequence("Shift+F12"));edit->addAction("Rename Symbol (clangd)",this,&MainWindow::renameSymbol,QKeySequence("Ctrl+F2"));edit->addAction("Hover / Type Info (clangd)",this,&MainWindow::showHover,QKeySequence("Ctrl+K"));edit->addAction("Smart Completion (clangd)",this,&MainWindow::requestSmartCompletion,QKeySequence("Ctrl+Alt+Space"));
    auto*sc=menuBar()->addMenu("Scene");sc->addAction("New Scene",this,&MainWindow::newScene);sc->addAction("Save Scene",this,&MainWindow::saveScene);sc->addSeparator();sc->addAction("Add Object",this,&MainWindow::addSceneObject);sc->addAction("Duplicate Object",this,&MainWindow::duplicateSceneObject);sc->addAction("Delete Object",this,&MainWindow::deleteSceneObject);sc->addSeparator();sc->addAction("Create Prefab",this,&MainWindow::createPrefab);sc->addAction("Instantiate Prefab",this,&MainWindow::instantiatePrefab);
    auto*b=menuBar()->addMenu("Build");b->addAction("Build",this,&MainWindow::buildProject,QKeySequence("Ctrl+B"));b->addAction("Build All Profiles",this,&MainWindow::buildAllProfiles);b->addAction("Build & Play",this,&MainWindow::buildAndRun,QKeySequence("F5"));b->addAction("Pause / Resume",m_gameView,&GameView::pause,QKeySequence("F6"));b->addAction("Frame Step",m_gameView,&GameView::frameStep,QKeySequence("F7"));b->addAction("Stop",this,&MainWindow::stopRun,QKeySequence("Shift+F5"));auto*live=b->addAction("Live Rebuild + Relaunch");live->setCheckable(true);connect(live,&QAction::toggled,this,&MainWindow::setLiveReload);b->addSeparator();b->addAction("Regenerate Runtime Templates",this,&MainWindow::regenerateRuntimeTemplates);
    auto*d=menuBar()->addMenu("Debug");d->addAction("Start / Show GDB",this,&MainWindow::startDebugger,QKeySequence("F9"));d->addAction("Toggle Breakpoint",this,&MainWindow::toggleBreakpoint,QKeySequence("F8"));
    auto*ps=menuBar()->addMenu("PS2");ps->addAction("Run in PCSX2",this,&MainWindow::runPCSX2);ps->addAction("Restart PCSX2",this,&MainWindow::restartPCSX2);ps->addAction("Deploy via ps2client",this,&MainWindow::sendToPS2);ps->addAction("Disc / Deploy Manager",this,&MainWindow::openDiscDeploy);ps->addAction("Environment Doctor",this,&MainWindow::openEnvironmentDoctor);ps->addAction("Refresh Environment",this,&MainWindow::refreshEnvironment);
    auto*tools=menuBar()->addMenu("Tools");tools->addAction("Convert Modern Model (glTF/FBX/DAE)",this,&MainWindow::convertModernModel);tools->addAction("First-Run Setup",this,&MainWindow::openSetupWizard);tools->addAction("Dependency Manager",this,&MainWindow::openDependencyManager);tools->addAction("Validation Center",this,&MainWindow::openValidationCenter);tools->addAction("Create Support Bundle",this,&MainWindow::createSupportBundle);
    auto*help=menuBar()->addMenu("Help");help->addAction("Documentation",this,&MainWindow::openDocumentation,QKeySequence("F1"));auto*samples=help->addMenu("Samples");samples->addAction("Create 2D Sample Files",this,&MainWindow::create2DSample);samples->addAction("Create 3D Sample Files",this,&MainWindow::create3DSample);samples->addAction("Create Validation Game Checklist",this,&MainWindow::createValidationSample);help->addSeparator();help->addAction("Check for Updates",this,&MainWindow::checkForUpdates);
}
void MainWindow::applyTheme(){qApp->setStyle("Fusion");qApp->setStyleSheet("QMainWindow,QWidget{background:#141820;color:#dbe2ee}QPlainTextEdit,QTreeWidget,QListWidget,QLineEdit,QComboBox,QSpinBox,QDoubleSpinBox{background:#0d1118;color:#e6edf7;border:1px solid #2b3442}QToolBar{background:#10141b;border:0}QTabBar::tab{background:#1b212c;padding:8px 14px}QTabBar::tab:selected{background:#2a3546}QPushButton{background:#263143;border:1px solid #3a4960;padding:6px}QDockWidget::title{background:#1a202a;padding:5px}");}
void MainWindow::newProject(){NewProjectDialog d(this);if(d.exec()!=QDialog::Accepted)return;createProject(d.projectPath(),d.projectName(),d.projectType(),d.engineBackend());}
void MainWindow::createProject(const QString&base,const QString&name,const QString&type,const QString&engineBackend){
 QString root=QDir(base).filePath(name);
 auto write=[&](QString p,QString t){QDir().mkpath(QFileInfo(root+"/"+p).absolutePath());QFile f(root+"/"+p);if(f.open(QIODevice::WriteOnly|QIODevice::Truncate|QIODevice::Text))f.write(t.toUtf8());};
 if(engineBackend=="tyra"){
   for(auto d:{"src","inc","obj","bin","res","scripts"})QDir().mkpath(root+"/"+d);
   QString c=name;c.replace(QRegularExpression("[^A-Za-z0-9_]"),"_");if(c.isEmpty())c="TyraGame";if(c[0].isDigit())c.prepend("Game_");
   write("src/main.cpp",tyraMainSource(c));write("inc/"+c+".hpp",tyraGameHeader(c));write("src/"+c+".cpp",tyraGameSource(c));write("Makefile",tyraMakefile(name));write("run.ps1",tyraRunScript());
   QJsonObject m{{"name",name},{"type",type},{"version","0.18"},{"engine","tyra"},{"renderer","Tyra/VU1"},{"profiles",QJsonArray{"Debug","Release"}}};write("ps2studio.json",QString::fromUtf8(QJsonDocument(m).toJson()));
   m_projectRoot=root;m_assetDb->setProjectRoot(root);m_gameView->setProjectRoot(root);m_profiler->setProjectRoot(root);QDir().mkpath(projectMetaDir());writeProjectConfig();loadProjectTree(root);openFile(root+"/src/main.cpp");updateEnvironmentPanel();return;
 }
 for(auto d:{"src","include","runtime","generated","scenes","assets/textures","assets/models","assets/audio","assets/fonts","assets/animations","prefabs","scripts","iop"})QDir().mkpath(root+"/"+d);
 write("src/main.cpp",ps2MainSource(type));write("runtime/PS2SceneRuntime.h",ps2RuntimeHeader());write("runtime/PS2SceneRuntime.cpp",ps2RuntimeSource());write("runtime/vu1_transform.vsm",ps2VuProgram());write("Makefile",ps2Makefile(name));write("scripts/PlayerController.cpp",ps2ComponentExample("PlayerController"));
 QJsonObject m{{"name",name},{"type",type},{"version","0.18"},{"engine","native"},{"renderer",type.startsWith("2D")?"gsKit2D":"gsKit3D"},{"profiles",QJsonArray{"Debug","Optimized","Release"}}};write("ps2studio.json",QString::fromUtf8(QJsonDocument(m).toJson()));
 m_projectRoot=root;ensureIopSkeleton();m_assetDb->setProjectRoot(root);m_gameView->setProjectRoot(root);m_profiler->setProjectRoot(root);QDir().mkpath(projectMetaDir());writeProjectConfig();newScene();
}
void MainWindow::openProject(){auto dir=QFileDialog::getExistingDirectory(this,"Open PS2 Project");if(dir.isEmpty())return;for(auto d:{"src","include","runtime","generated","scenes","assets/textures","assets/models","assets/audio","assets/fonts","assets/animations","prefabs","scripts","iop"})QDir().mkpath(dir+"/"+d);QFile meta(dir+"/ps2studio.json");QJsonObject mo;if(meta.open(QIODevice::ReadOnly)){mo=QJsonDocument::fromJson(meta.readAll()).object();meta.close();}QString oldVersion=mo.value("version").toString();if(oldVersion!="0.17"){if(QFileInfo::exists(dir+"/ps2studio.json"))QFile::copy(dir+"/ps2studio.json",dir+"/ps2studio.json.pre017.bak");mo["version"]="0.17";if(!mo.contains("name"))mo["name"]=QFileInfo(dir).fileName();if(meta.open(QIODevice::WriteOnly|QIODevice::Truncate))meta.write(QJsonDocument(mo).toJson(QJsonDocument::Indented));}loadProjectTree(dir);m_assetDb->setProjectRoot(dir);m_gameView->setProjectRoot(dir);m_profiler->setProjectRoot(dir);auto cfg=readProjectConfig();m_ps2Host=cfg.value("ps2Host").toString(m_ps2Host);m_pcsx2Path=cfg.value("pcsx2Path").toString();m_autosaveSeconds=cfg.value("autosaveSeconds").toInt(60);if(m_profileCombo)m_profileCombo->setCurrentText(cfg.value("profile").toString(m_profileCombo->currentText()));if(m_targetCombo)m_targetCombo->setCurrentText(cfg.value("target").toString(m_targetCombo->currentText()));if(m_videoPresetCombo)m_videoPresetCombo->setCurrentText(cfg.value("videoPreset").toString(m_videoPresetCombo->currentText()));if(m_autosaveTimer)m_autosaveTimer->setInterval(qMax(15,m_autosaveSeconds)*1000);loadDefaultScene();rememberProject(dir);updateFileWatchers();recoverAutosave();}
void MainWindow::loadProjectTree(const QString&root){m_projectRoot=root;m_projectTree->clear();auto*top=new QTreeWidgetItem(QStringList{QFileInfo(root).fileName()});top->setExpanded(true);m_projectTree->addTopLevelItem(top);std::function<void(QTreeWidgetItem*,QString)>add=[&](QTreeWidgetItem*p,QString path){QDir d(path);for(const auto&fi:d.entryInfoList(QDir::Dirs|QDir::Files|QDir::NoDotAndDotDot,QDir::DirsFirst|QDir::Name)){auto*it=new QTreeWidgetItem(p,QStringList{fi.fileName()});it->setData(0,Qt::UserRole,fi.absoluteFilePath());if(fi.isDir())add(it,fi.absoluteFilePath());}};add(top,root);m_projectTree->expandToDepth(1);m_statusTarget->setText("Project: "+root);}
void MainWindow::openFile(const QString&path){const QString absolute=QFileInfo(path).absoluteFilePath();for(int i=0;i<m_editorTabs->count();++i){auto*ed=dynamic_cast<CodeEditor*>(m_editorTabs->widget(i));if(ed&&ed->filePath()==absolute){m_editorTabs->setCurrentIndex(i);m_workspaceTabs->setCurrentWidget(m_editorTabs);ed->setFocus();return;}}auto*ed=new CodeEditor;QString error;if(!ed->loadFile(absolute,&error)){delete ed;QMessageBox::warning(this,"Open File",error);return;}connect(ed->document(),&QTextDocument::modificationChanged,this,[this,ed](bool){updateEditorTab(ed);});connect(ed->document(),&QTextDocument::contentsChanged,this,[this,ed]{if(m_clangd&&m_clangd->isRunning())m_clangd->changeDocument(ed->filePath(),ed->toPlainText());});QString clangd=findExecutable({"clangd","clangd.exe"});if(!clangd.isEmpty()&&!m_projectRoot.isEmpty()){if(!m_clangd->isRunning())m_clangd->start(clangd,m_projectRoot);m_clangd->openDocument(absolute,ed->toPlainText());}int i=m_editorTabs->addTab(ed,QFileInfo(absolute).fileName());m_editorTabs->setCurrentIndex(i);m_workspaceTabs->setCurrentWidget(m_editorTabs);ed->setFocus();}
void MainWindow::saveCurrent(){if(auto*ed=currentEditor())saveEditor(ed);if(!m_scene->filePath().isEmpty()&&m_sceneDirty)saveScene();}
void MainWindow::saveCurrentAs(){auto*ed=currentEditor();if(!ed)return;QString path=QFileDialog::getSaveFileName(this,"Save Source As",ed->filePath().isEmpty()?m_projectRoot:ed->filePath());if(path.isEmpty())return;QString err;if(!ed->saveFileAs(path,&err))QMessageBox::warning(this,"Save As",err);else{updateEditorTab(ed);loadProjectTree(m_projectRoot);}}
void MainWindow::newScene(){m_scene->clear();auto&c=m_scene->addObject("Camera","Main Camera");c.position={0,0,-6};auto&p=m_scene->addObject("Sprite","Player");p.tag="Player";p.position={120,120,0};p.colliderEnabled=true;p.rigidBody=true;p.kinematic=true;p.script="PlayerController.cpp";m_scene->setFilePath(m_projectRoot.isEmpty()?QString():m_projectRoot+"/scenes/Main.ps2scene");refreshHierarchy();}
void MainWindow::loadDefaultScene(){QString path=m_projectRoot+"/scenes/Main.ps2scene",e;if(QFileInfo::exists(path)){if(!m_scene->load(path,&e))appendOutput("Scene load failed: "+e+"\n");}else{newScene();saveScene();}}
void MainWindow::saveScene(){if(m_projectRoot.isEmpty())return;QString path=m_scene->filePath().isEmpty()?m_projectRoot+"/scenes/Main.ps2scene":m_scene->filePath();QString e;if(!m_scene->save(path,&e))QMessageBox::warning(this,"Save Scene",e);else{m_scene->setFilePath(path);m_sceneDirty=false;loadProjectTree(m_projectRoot);updateFileWatchers();}}
void MainWindow::addSceneObject(){QStringList types={"Sprite","Mesh","Camera","Light","Text","Panel","Button","Image","AudioSource","Empty"};bool ok=false;QString t=QInputDialog::getItem(this,"Add Scene Object","Type",types,0,false,&ok);if(!ok)return;auto&o=m_scene->addObject(t,t);selectObject(o.id);}void MainWindow::deleteSceneObject(){if(m_selectedObjectId.isEmpty())return;m_scene->removeObject(m_selectedObjectId);m_selectedObjectId.clear();m_inspector->setObjectId({});}void MainWindow::duplicateSceneObject(){if(m_selectedObjectId.isEmpty())return;auto&o=m_scene->duplicateObject(m_selectedObjectId);selectObject(o.id);}
void MainWindow::createPrefab(){if(m_projectRoot.isEmpty()||m_selectedObjectId.isEmpty())return;QString path=QFileDialog::getSaveFileName(this,"Create Prefab",m_projectRoot+"/prefabs/Object.ps2prefab","PS2 Prefab (*.ps2prefab)");if(path.isEmpty())return;QString e;if(!m_scene->savePrefab(m_selectedObjectId,path,&e))QMessageBox::warning(this,"Prefab",e);else loadProjectTree(m_projectRoot);}void MainWindow::instantiatePrefab(){if(m_projectRoot.isEmpty())return;QString path=QFileDialog::getOpenFileName(this,"Instantiate Prefab",m_projectRoot+"/prefabs","PS2 Prefab (*.ps2prefab)");if(path.isEmpty())return;QString e;if(!m_scene->instantiatePrefab(path,&e))QMessageBox::warning(this,"Prefab",e);}
void MainWindow::refreshHierarchy(){if(!m_hierarchy)return;m_hierarchy->clear();for(const auto&o:m_scene->objects()){auto*it=new QTreeWidgetItem(QStringList{o.name+"  ["+o.type+"]"});it->setData(0,Qt::UserRole,o.id);m_hierarchy->addTopLevelItem(it);if(o.id==m_selectedObjectId)it->setSelected(true);}}void MainWindow::selectObject(const QString&id){m_selectedObjectId=id;m_inspector->setObjectId(id);m_scene2D->setSelectedId(id);m_view3D->setSelectedId(id);for(int i=0;i<m_hierarchy->topLevelItemCount();++i)m_hierarchy->topLevelItem(i)->setSelected(m_hierarchy->topLevelItem(i)->data(0,Qt::UserRole).toString()==id);}
void MainWindow::importAsset(){if(m_projectRoot.isEmpty())return;auto fs=QFileDialog::getOpenFileNames(this,"Import PS2 Assets",{},"PS2 Runtime Assets (*.png *.bmp *.jpg *.jpeg *.tga *.obj *.ps2skin *.ps2anim *.wav);;All Files (*.*)");for(const auto&f:fs){QString e;if(m_assetDb->importAsset(f,&e).isEmpty()&&!e.isEmpty())appendOutput("Asset import failed: "+e+"\n");}loadProjectTree(m_projectRoot);m_profiler->refresh();updateFileWatchers();}void MainWindow::refreshAssets(){if(!m_assets)return;m_assets->clear();m_assets->addItems(m_assetDb->assets());}
QString MainWindow::findExecutable(const QStringList&ns)const{QStringList dirs;auto env=QProcessEnvironment::systemEnvironment();QString ps2dev=env.value("PS2DEV");if(ps2dev.isEmpty()&&QFileInfo::exists("C:/ps2dev"))ps2dev="C:/ps2dev";QString sdk=env.value("PS2SDK");if(sdk.isEmpty()&&!ps2dev.isEmpty())sdk=ps2dev+"/ps2sdk";if(!ps2dev.isEmpty())dirs<<ps2dev+"/bin"<<ps2dev+"/ee/bin"<<ps2dev+"/iop/bin"<<ps2dev+"/dvp/bin";if(!sdk.isEmpty())dirs<<sdk+"/bin";
#ifdef Q_OS_WIN
 dirs<<"C:/msys64/usr/bin"<<"C:/msys64/mingw64/bin"<<"C:/Program Files/LLVM/bin"<<"C:/Program Files/PCSX2"<<"C:/Program Files/PCSX2 Nightly";QString la=qEnvironmentVariable("LOCALAPPDATA");if(!la.isEmpty())dirs<<la+"/Microsoft/WinGet/Links"<<la+"/Programs/PCSX2";
#endif
 for(const auto&n:ns){auto p=QStandardPaths::findExecutable(n);if(!p.isEmpty())return p;QStringList names={n};
#ifdef Q_OS_WIN
 if(!n.endsWith(".exe",Qt::CaseInsensitive))names<<n+".exe";
#endif
 for(const auto&d:dirs)for(const auto&name:names){QString c=QDir(d).filePath(name);if(QFileInfo(c).isFile())return QDir::cleanPath(c);}}return{};}void MainWindow::appendOutput(const QString&t){m_buildOutput->moveCursor(QTextCursor::End);m_buildOutput->insertPlainText(t);m_buildOutput->moveCursor(QTextCursor::End);}QString MainWindow::findElf()const{auto f=QDir(m_projectRoot).entryInfoList({"*.elf"},QDir::Files,QDir::Time);return f.isEmpty()?QString():f.first().absoluteFilePath();}

bool MainWindow::exportAllScenes(QString*error){
    QDir().mkpath(m_projectRoot+"/generated");saveScene();
    QStringList paths=QDir(m_projectRoot+"/scenes").entryList({"*.ps2scene"},QDir::Files,QDir::Name);if(paths.isEmpty())paths<<"Main.ps2scene";
    QString header="#pragma once\n#include \"PS2SceneRuntime.h\"\nextern const PS2Scene g_scenes[];\nextern const int g_sceneCount;\n";
    QString source="#include \"PS2SceneData.h\"\n\n";QStringList sceneRows;QMap<QString,QString> components;int sn=0;
    for(const auto&fn:paths){
        SceneDocument d;QString e;if(!d.load(m_projectRoot+"/scenes/"+fn,&e)){if(error)*error=e;return false;}
        QString arr=QString("scene_%1_entities").arg(sn);source+=QString("static const PS2Entity %1[] = {\n").arg(arr);
        for(const auto&o:d.objects()){
            if(!o.script.trimmed().isEmpty()){
                QString file=QFileInfo(o.script).fileName();if(QFileInfo(file).suffix().isEmpty())file+=".cpp";
                QString full=m_projectRoot+"/scripts/"+file;if(!QFileInfo::exists(full)){if(error)*error=QString("Component '%1' is assigned to '%2' but scripts/%3 does not exist.").arg(o.script,o.name,file);return false;}
                QString sym=QFileInfo(file).completeBaseName();sym.replace(QRegularExpression("[^A-Za-z0-9_]"),"_");if(!sym.isEmpty()&&sym[0].isDigit())sym.prepend("C_");components[file]=sym;
            }
            QStringList v;
            v<<cpp(o.name)<<cstrLiteral(o.tag)<<QString::number(entityType(o.type));
            v<<("{"+QStringList{f32(o.position.x()),f32(o.position.y()),f32(o.position.z()),f32(o.rotation.x()),f32(o.rotation.y()),f32(o.rotation.z()),f32(o.scale.x()),f32(o.scale.y()),f32(o.scale.z())}.join(",")+"}");
            v<<f32(o.velocity.x())<<f32(o.velocity.y())<<f32(o.velocity.z());
            v<<cstrAsset(o.asset)<<cstrAsset(o.materialTexture)<<f32(o.materialTint.x())<<f32(o.materialTint.y())<<f32(o.materialTint.z())<<f32(o.materialAlpha)<<QString::number(o.materialUnlit?1:0)<<QString::number(o.materialTransparent?1:0)<<f32(o.lightIntensity);
            v<<cstrAsset(o.animationAsset)<<f32(o.animationSpeed)<<QString::number(o.animationLoop?1:0)<<QString::number(o.animationAutoplay?1:0)<<cstrAsset(o.script);
            v<<cstrLiteral(o.uiText)<<cstrLiteral(o.uiAction)<<f32(o.uiColor.x())<<f32(o.uiColor.y())<<f32(o.uiColor.z())<<f32(o.uiWidth)<<f32(o.uiHeight)<<QString::number(o.uiSelectable?1:0)<<cstrLiteral(o.nextScene);
            v<<f32(o.colliderSize.x())<<f32(o.colliderSize.y())<<f32(o.colliderSize.z())<<QString::number(o.colliderEnabled?1:0)<<QString::number(o.trigger?1:0)<<QString::number(o.rigidBody?1:0)<<QString::number(o.kinematic?1:0)<<QString::number(o.useGravity?1:0)<<f32(o.gravityScale)<<f32(o.mass)<<f32(o.restitution)<<f32(o.friction)<<QString::number(o.collisionLayer)<<QString::number(o.collisionMask);
            v<<QString::number(o.particleEmitter?1:0)<<QString::number(o.particleCount)<<f32(o.particleLife);
            v<<cstrAsset(o.audioAsset)<<QString::number(o.audioAutoplay?1:0)<<QString::number(o.audioLoop?1:0)<<f32(o.audioVolume)<<f32(o.audioPan);
            source+="{"+v.join(",")+"},\n";
        }
        source+="};\n";sceneRows<<QString("{%1,%2,sizeof(%2)/sizeof(%2[0])}").arg(cpp(QFileInfo(fn).completeBaseName())).arg(arr);sn++;
    }
    source+="const PS2Scene g_scenes[] = {\n"+sceneRows.join(",\n")+"\n};\nconst int g_sceneCount = sizeof(g_scenes)/sizeof(g_scenes[0]);\n";
    QFile h(m_projectRoot+"/generated/PS2SceneData.h");if(!h.open(QIODevice::WriteOnly|QIODevice::Truncate|QIODevice::Text)){if(error)*error=h.errorString();return false;}h.write(header.toUtf8());
    QFile c(m_projectRoot+"/generated/PS2SceneData.cpp");if(!c.open(QIODevice::WriteOnly|QIODevice::Truncate|QIODevice::Text)){if(error)*error=c.errorString();return false;}c.write(source.toUtf8());

    QString reg="#include \"PS2SceneRuntime.h\"\n#include <string.h>\n\n";
    for(auto it=components.cbegin();it!=components.cend();++it){const QString&s=it.value();reg+=QString("extern \"C\" void %1_Start(PS2SceneRuntime*,PS2RuntimeEntity*);\nextern \"C\" void %1_Update(PS2SceneRuntime*,PS2RuntimeEntity*,float);\nextern \"C\" void %1_OnCollision(PS2SceneRuntime*,PS2RuntimeEntity*,const PS2CollisionEvent*);\nextern \"C\" void %1_OnAction(PS2SceneRuntime*,PS2RuntimeEntity*,const char*);\n").arg(s);}
    auto dispatch=[&](const QString&sig,const QString&call){QString out=sig+"{if(!script)return;";for(auto it=components.cbegin();it!=components.cend();++it){QString stem=QFileInfo(it.key()).completeBaseName();out+=QString("if(strcmp(script,%1)==0||strcmp(script,%2)==0){%3;return;}").arg(cpp(it.key()),cpp(stem),call.arg(it.value()));}out+="}\n";return out;};
    reg+=dispatch("void ps2studio_component_start(const char*script,PS2SceneRuntime*r,PS2RuntimeEntity*s)",QString("%1_Start(r,s)"));
    reg+=dispatch("void ps2studio_component_update(const char*script,PS2SceneRuntime*r,PS2RuntimeEntity*s,float dt)",QString("%1_Update(r,s,dt)"));
    reg+=dispatch("void ps2studio_component_collision(const char*script,PS2SceneRuntime*r,PS2RuntimeEntity*s,const PS2CollisionEvent*e)",QString("%1_OnCollision(r,s,e)"));
    reg+=dispatch("void ps2studio_component_action(const char*script,PS2SceneRuntime*r,PS2RuntimeEntity*s,const char*a)",QString("%1_OnAction(r,s,a)"));
    QFile cr(m_projectRoot+"/generated/PS2ComponentRegistry.cpp");if(!cr.open(QIODevice::WriteOnly|QIODevice::Truncate|QIODevice::Text)){if(error)*error=cr.errorString();return false;}cr.write(reg.toUtf8());
    return true;
}
void MainWindow::buildProject(){
    if(m_projectRoot.isEmpty())return;
    QFile tm(m_projectRoot+"/ps2studio.json");QJsonObject tmo;if(tm.open(QIODevice::ReadOnly))tmo=QJsonDocument::fromJson(tm.readAll()).object();
    bool isTyra=tmo.value("engine").toString()=="tyra";if(m_process->state()!=QProcess::NotRunning){QMessageBox::information(this,"Build","A build/tool process is already running.");return;}if(!saveAllEditors())return;m_buildOutput->clear();m_process->setProcessEnvironment(buildEnvironment());
    if(isTyra){QString tyra=qEnvironmentVariable("TYRA");if(tyra.isEmpty()&&QFileInfo::exists("C:/tyra/Makefile.base"))tyra="C:/tyra";if(tyra.isEmpty()){appendOutput("Tyra Engine not found. Run BOOTSTRAP.cmd.\n");return;}auto pe=buildEnvironment();pe.insert("TYRA",tyra);m_process->setProcessEnvironment(pe);QString make=resolveMake();if(make.isEmpty()){appendOutput("GNU make not found.\n");return;}m_process->setWorkingDirectory(m_projectRoot);appendOutput("PS2 Studio Tyra build\nEngine: "+tyra+"\n");m_process->start(make,{});return;}
    saveScene();const int target=m_targetCombo->currentIndex();
    if(target==2){QString err;if(!ensureIopSkeleton(&err)){appendOutput("IOP setup failed: "+err+"\n");return;}QString make=resolveMake();if(make.isEmpty()){appendOutput("GNU make not found. Use Tools > Dependency Manager > Install All.\n");return;}m_process->setWorkingDirectory(m_projectRoot+"/iop");appendOutput("PS2 Studio IOP build\n> "+make+"\n");m_process->start(make,{});return;}
    if(target==3){QString dvp=findExecutable({"dvp-as"});QString src=m_projectRoot+"/runtime/vu1_transform.vsm";QString out=m_projectRoot+"/runtime/vu1_transform.o";if(dvp.isEmpty()){appendOutput("dvp-as not found.\n");return;}if(!QFileInfo::exists(src)){appendOutput("No runtime/vu1_transform.vsm source found.\n");return;}m_process->setWorkingDirectory(m_projectRoot);appendOutput("PS2 Studio VU/DVP assembly\n> "+dvp+" "+src+" -o "+out+"\n");m_process->start(dvp,{src,"-o",out});return;}
    appendOutput("PS2 Studio EE pipeline\n- compiling textures, static/skinned meshes, animations and WAV/ADPCM audio\n");auto ar=AssetCompiler::compileProject(m_projectRoot);if(!ar.ok){appendOutput("Asset compiler failed: "+ar.error+"\n");return;}appendOutput(QString("Assets: %1 textures, %2 static meshes, %3 skinned meshes, %4 animations, %5 sounds (%6 ADPCM)\n").arg(ar.textures).arg(ar.meshes).arg(ar.skinnedMeshes).arg(ar.animations).arg(ar.sounds).arg(ar.adpcmSounds));QString e;if(!exportAllScenes(&e)){appendOutput("Scene compiler failed: "+e+"\n");return;}prepareRuntimeSupportFiles();QString make=resolveMake();if(make.isEmpty()){appendOutput("GNU make not found. Use Tools > Dependency Manager > Install All.\n");return;}QStringList args;args<<("PROFILE="+m_profileCombo->currentText());if(target==1)args<<"VU1=1";m_process->setWorkingDirectory(m_projectRoot);appendOutput("> "+make+" "+args.join(' ')+"\n");m_process->start(make,args);
}
void MainWindow::buildAllProfiles(){
    if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Build All Profiles","Open a project first.");return;}
    if(m_targetCombo->currentIndex()>=2){QMessageBox::information(this,"Build All Profiles","Profile validation applies to EE builds. Building the selected IOP/VU target once instead.");buildProject();return;}
    if(m_process->state()!=QProcess::NotRunning){QMessageBox::information(this,"Build All Profiles","Another build/tool process is already running.");return;}
    if(!saveAllEditors())return;QString err;if(!exportAllScenes(&err)){appendOutput("Scene export failed: "+err+"\n");return;}auto cr=AssetCompiler::compileProject(m_projectRoot);if(!cr.ok){appendOutput("Asset compile failed: "+cr.error+"\n");return;}
    auto make=resolveMake();if(make.isEmpty()){appendOutput("GNU make not found.\n");return;}m_process->setProcessEnvironment(buildEnvironment());
    appendOutput("\n=== Validation build: Debug / Optimized / Release ===\n");
    auto profiles=std::make_shared<QStringList>(QStringList{"Debug","Optimized","Release"});
    auto index=std::make_shared<int>(0);auto failures=std::make_shared<QStringList>();auto next=std::make_shared<std::function<void()>>();
    *next=[this,make,profiles,index,failures,next](){if(*index>=profiles->size()){appendOutput(QString("=== Validation builds complete. Failures: %1 ===\n").arg(failures->isEmpty()?"none":failures->join(", ")));if(failures->isEmpty())QMessageBox::information(this,"Build All Profiles","Debug, Optimized and Release builds all completed successfully.");else QMessageBox::warning(this,"Build All Profiles","Failed profiles: "+failures->join(", "));return;}QString profile=profiles->at((*index)++);appendOutput("\n--- PROFILE="+profile+" ---\n");m_process->setWorkingDirectory(m_projectRoot);QMetaObject::Connection*c=new QMetaObject::Connection;*c=connect(m_process,qOverload<int,QProcess::ExitStatus>(&QProcess::finished),this,[this,profile,failures,next,c](int code,QProcess::ExitStatus){QObject::disconnect(*c);delete c;if(code!=0)failures->append(profile);(*next)();});m_process->start(make,{"PROFILE="+profile});};
    (*next)();
}
void MainWindow::buildAndRun(){if(m_projectRoot.isEmpty())return;if(m_targetCombo->currentIndex()>=2){QMessageBox::information(this,"Build & Play","Build & Play requires an EE executable target.");buildProject();return;}m_gameView->play();m_workspaceTabs->setCurrentWidget(m_gameView);m_runAfterBuild=true;buildProject();if(m_process->state()==QProcess::NotRunning)m_runAfterBuild=false;}
void MainWindow::runPCSX2(){auto elf=findElf();if(elf.isEmpty()){appendOutput("Build first: no ELF found.\n");return;}auto exe=resolvePCSX2();if(exe.isEmpty()){QMessageBox::warning(this,"PS2 Studio","PCSX2 was not found. Install it from Dependency Manager or set the executable in Project Settings.");return;}m_pcsx2Path=exe;writeProjectConfig();if(m_runProcess->state()!=QProcess::NotRunning)m_runProcess->kill();m_runProcess->setWorkingDirectory(m_projectRoot);m_runProcess->setProcessEnvironment(buildEnvironment());appendOutput("\nLaunching PCSX2: "+elf+"\n");m_runProcess->start(exe,{elf});}
void MainWindow::stopRun(){m_gameView->stop();if(m_runProcess->state()!=QProcess::NotRunning){m_runProcess->terminate();if(!m_runProcess->waitForFinished(1000))m_runProcess->kill();}appendOutput("\nStopped play session.\n");}
void MainWindow::sendToPS2(){auto elf=findElf();auto client=findExecutable({"ps2client"});if(client.isEmpty()){QMessageBox::warning(this,"PS2 Studio","ps2client not found. Run ps2link on the console and install the PS2DEV client.");return;}if(elf.isEmpty()){QMessageBox::information(this,"PS2 Studio","Build first.");return;}m_process->setWorkingDirectory(m_projectRoot);QString host="host:"+QFileInfo(elf).fileName();QProcessEnvironment pe=buildEnvironment();pe.insert("PS2HOST",m_ps2Host);m_process->setProcessEnvironment(pe);appendOutput("\nPS2 target: "+m_ps2Host+"\n> ps2client execee "+host+"\n");m_process->start(client,{"execee",host});}
void MainWindow::startDebugger(){auto gdb=findExecutable({"mips64r5900el-ps2-elf-gdb","ps2gdb"});if(gdb.isEmpty()){QMessageBox::warning(this,"Debugger","No PS2 GDB client found.");return;}if(m_debugDock){m_debugDock->show();m_debugDock->raise();}if(!m_debugger->isRunning()){auto elf=findElf();if(!m_debugger->startDebugger(gdb,elf,m_projectRoot))QMessageBox::warning(this,"Debugger","GDB could not be started.");}}
void MainWindow::openDiscDeploy(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Disc / Deploy","Open a project first.");return;}auto elf=findElf();DiscDeployDialog d(m_projectRoot,elf,this);d.exec();}
void MainWindow::openEnvironmentDoctor(){EnvironmentDoctorDialog d(m_projectRoot,m_pcsx2Path,m_ps2Host,this);d.exec();}
void MainWindow::openSetupWizard(){SetupWizardDialog d(this);if(d.exec()==QDialog::Accepted){QSettings st("PS2Studio","PS2Studio");m_pcsx2Path=st.value("pcsx2Path",m_pcsx2Path).toString();m_ps2Host=st.value("ps2Host",m_ps2Host).toString();updateEnvironmentPanel();writeProjectConfig();}}
void MainWindow::openDocumentation(){DocumentationDialog d(this);d.exec();}
void MainWindow::openValidationCenter(){ValidationCenterDialog d(m_projectRoot,m_pcsx2Path,m_ps2Host,this);d.exec();}
void MainWindow::checkForUpdates(){auto*u=new UpdateChecker(this);u->check(this);}
void MainWindow::createSupportBundle(){QString p;if(SupportBundle::create(m_projectRoot,this,&p))statusBar()->showMessage("Support bundle created: "+p,5000);}
void MainWindow::create2DSample(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Samples","Open or create a project first.");return;}QString e;if(!SampleProjectGenerator::create(m_projectRoot,"2D",&e))QMessageBox::warning(this,"2D Sample",e);else{loadProjectTree(m_projectRoot);QMessageBox::information(this,"2D Sample","2D sample guidance was added under samples/. Create a Sprite, assign a texture, add a collider, and validate in Game View then PCSX2.");}}
void MainWindow::create3DSample(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Samples","Open or create a project first.");return;}QString e;if(!SampleProjectGenerator::create(m_projectRoot,"3D",&e))QMessageBox::warning(this,"3D Sample",e);else{loadProjectTree(m_projectRoot);QMessageBox::information(this,"3D Sample","3D sample guidance was added under samples/. Import an OBJ with UVs, assign material texture, camera and light.");}}
void MainWindow::createValidationSample(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Validation Game","Open or create a project first.");return;}QString e;if(!SampleProjectGenerator::create(m_projectRoot,"Validation",&e))QMessageBox::warning(this,"Validation Game",e);else{loadProjectTree(m_projectRoot);openValidationCenter();}}
void MainWindow::refreshEnvironment(){updateEnvironmentPanel();}
void MainWindow::updateEnvironmentPanel(){auto env=buildEnvironment();QStringList s;for(auto k:{"PS2DEV","PS2SDK","GSKIT"}){auto v=env.value(k);s<<QString("%1 %2%3").arg(v.isEmpty()?"○":"✓",k,v.isEmpty()?"":" = "+v);}auto ex=[&](QString l,QStringList n){s<<QString("%1 %2").arg(findExecutable(n).isEmpty()?"○":"✓",l);};ex("GNU make",{"make","mingw32-make"});ex("EE compiler",{"mips64r5900el-ps2-elf-g++"});ex("IOP compiler",{"mipsel-none-elf-gcc"});ex("DVP assembler / VU1",{"dvp-as"});ex("ps2gdb/GDB",{"mips64r5900el-ps2-elf-gdb","ps2gdb"});ex("ps2client",{"ps2client"});QString pc=resolvePCSX2();s<<QString("%1 PCSX2%2").arg(pc.isEmpty()?"○":"✓",pc.isEmpty()?"":" = "+pc);s<<"PS2 host = "+m_ps2Host;m_envSummary->setText(s.join("\n"));}



void MainWindow::findInProject(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Find in Project","Open a project first.");return;}ProjectSearchDialog d(m_projectRoot,this);d.setOpenCallback([this](const QString&f,int line){openFile(f);if(auto*ed=currentEditor())ed->gotoLine(line,1);});d.exec();}
void MainWindow::goToDefinition(){auto*ed=currentEditor();if(!ed)return;QString clangd=findExecutable({"clangd","clangd.exe"});if(clangd.isEmpty()){QMessageBox::information(this,"Code Intelligence","clangd was not found. Install LLVM from Dependency Manager/bootstrap.");return;}if(!m_clangd->isRunning()&&!m_clangd->start(clangd,m_projectRoot)){QMessageBox::warning(this,"clangd",m_clangd->lastError());return;}m_clangd->openDocument(ed->filePath(),ed->toPlainText());QTextCursor c=ed->textCursor();m_clangd->requestDefinition(ed->filePath(),c.blockNumber(),c.positionInBlock(),[this](QString file,int line,int col){if(file.isEmpty()){statusBar()->showMessage("clangd: definition not found",2500);return;}openFile(file);if(auto*e=currentEditor())e->gotoLine(line,col);});}
void MainWindow::restartPCSX2(){stopRun();QTimer::singleShot(250,this,&MainWindow::runPCSX2);}
void MainWindow::setLiveReload(bool enabled){m_liveReload=enabled;statusBar()->showMessage(enabled?"Live rebuild/relaunch enabled":"Live rebuild/relaunch disabled",2500);}
void MainWindow::convertModernModel(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Convert Model","Open a project first.");return;}QString in=QFileDialog::getOpenFileName(this,"Convert Model",{},"3D Models (*.gltf *.glb *.fbx *.dae)");if(in.isEmpty())return;QString out=m_projectRoot+"/assets/models/"+QFileInfo(in).completeBaseName()+".obj";QString blender=findExecutable({"blender","blender.exe"});QString assimp=findExecutable({"assimp","assimp.exe"});if(!assimp.isEmpty()){m_process->setWorkingDirectory(m_projectRoot);appendOutput("Converting model with Assimp: "+in+" -> "+out+"\n");m_process->start(assimp,{"export",in,out,"-fobj"});return;}if(!blender.isEmpty()){QString py=m_projectRoot+"/.ps2studio/convert_model.py";QDir().mkpath(m_projectRoot+"/.ps2studio");QFile f(py);if(f.open(QIODevice::WriteOnly|QIODevice::Truncate|QIODevice::Text)){f.write("import bpy,sys\\nargs=sys.argv[sys.argv.index('--')+1:]\\nsrc,dst=args[0],args[1]\\nbpy.ops.wm.read_factory_settings(use_empty=True)\\next=src.lower().split('.')[-1]\\nif ext in ('gltf','glb'): bpy.ops.import_scene.gltf(filepath=src)\\nelif ext=='fbx': bpy.ops.import_scene.fbx(filepath=src)\\nelif ext=='dae': bpy.ops.wm.collada_import(filepath=src)\\nbpy.ops.wm.obj_export(filepath=dst, export_materials=False)\\n");f.close();}m_process->setWorkingDirectory(m_projectRoot);appendOutput("Converting model with Blender: "+in+" -> "+out+"\n");m_process->start(blender,{"--background","--python",py,"--",in,out});return;}QMessageBox::information(this,"Convert Model","Install Assimp CLI or Blender. The converter will emit OBJ for the PS2 asset compiler.");}

QString MainWindow::projectMetaDir() const{return m_projectRoot.isEmpty()?QString():m_projectRoot+"/.ps2studio";}
QJsonObject MainWindow::readProjectConfig() const{QFile f(projectMetaDir()+"/project.json");if(!f.open(QIODevice::ReadOnly))return{};return QJsonDocument::fromJson(f.readAll()).object();}
void MainWindow::writeProjectConfig(){if(m_projectRoot.isEmpty())return;QDir().mkpath(projectMetaDir());QJsonObject o{{"format","PS2StudioProject"},{"version",1},{"ps2Host",m_ps2Host},{"pcsx2Path",m_pcsx2Path},{"autosaveSeconds",m_autosaveSeconds},{"profile",m_profileCombo?m_profileCombo->currentText():"Debug"},{"target",m_targetCombo?m_targetCombo->currentText():"EE / gsKit"},{"videoPreset",m_videoPresetCombo?m_videoPresetCombo->currentText():"NTSC 640x448"}};QFile f(projectMetaDir()+"/project.json");if(f.open(QIODevice::WriteOnly|QIODevice::Truncate))f.write(QJsonDocument(o).toJson(QJsonDocument::Indented));}
void MainWindow::rememberProject(const QString&p){QSettings st("PS2Studio","PS2Studio");QStringList r=st.value("recentProjects").toStringList();r.removeAll(p);r.prepend(p);while(r.size()>10)r.removeLast();st.setValue("recentProjects",r);st.setValue("lastProject",p);}
void MainWindow::loadAppState(){QSettings st("PS2Studio","PS2Studio");restoreGeometry(st.value("geometry").toByteArray());restoreState(st.value("windowState").toByteArray());if(m_profileCombo)m_profileCombo->setCurrentText(st.value("profile","Debug").toString());if(m_targetCombo)m_targetCombo->setCurrentText(st.value("target","EE / gsKit").toString());if(m_videoPresetCombo)m_videoPresetCombo->setCurrentText(st.value("videoPreset","NTSC 640x448").toString());}
void MainWindow::saveAppState(){QSettings st("PS2Studio","PS2Studio");st.setValue("geometry",saveGeometry());st.setValue("windowState",saveState());st.setValue("profile",m_profileCombo->currentText());st.setValue("target",m_targetCombo->currentText());st.setValue("videoPreset",m_videoPresetCombo->currentText());if(!m_projectRoot.isEmpty())st.setValue("lastProject",m_projectRoot);writeProjectConfig();}
void MainWindow::closeEvent(QCloseEvent*e){for(int i=m_editorTabs->count()-1;i>=0;--i)if(!closeEditorTab(i)){e->ignore();return;}if(m_sceneDirty)autosave();saveAppState();e->accept();}
void MainWindow::autosave(){if(m_projectRoot.isEmpty()||!m_sceneDirty)return;QDir().mkpath(projectMetaDir());QString err;QString path=projectMetaDir()+"/autosave.ps2scene";if(m_scene->save(path,&err)){QFile info(projectMetaDir()+"/autosave.json");if(info.open(QIODevice::WriteOnly|QIODevice::Truncate)){QJsonObject o{{"source",m_scene->filePath()},{"savedAt",QDateTime::currentDateTimeUtc().toString(Qt::ISODate)}};info.write(QJsonDocument(o).toJson());}statusBar()->showMessage("Autosaved scene",2000);}else appendOutput("Autosave failed: "+err+"\n");}
void MainWindow::recoverAutosave(){if(m_projectRoot.isEmpty())return;QString p=projectMetaDir()+"/autosave.ps2scene";if(!QFileInfo::exists(p))return;QFileInfo a(p),s(m_scene->filePath());if(s.exists()&&a.lastModified()<=s.lastModified())return;if(QMessageBox::question(this,"Recover Autosave","A newer autosaved scene exists. Recover it?")!=QMessageBox::Yes)return;QString err;if(m_scene->load(p,&err)){m_scene->setFilePath(s.exists()?s.absoluteFilePath():m_projectRoot+"/scenes/Main.ps2scene");m_sceneDirty=true;statusBar()->showMessage("Recovered autosave",3000);}else QMessageBox::warning(this,"Recover Autosave",err);}
void MainWindow::updateFileWatchers(){if(!m_watcher||m_projectRoot.isEmpty())return;if(!m_watcher->files().isEmpty())m_watcher->removePaths(m_watcher->files());if(!m_watcher->directories().isEmpty())m_watcher->removePaths(m_watcher->directories());QStringList dirs;QDirIterator dit(m_projectRoot+"/assets",QDir::Dirs|QDir::NoDotAndDotDot,QDirIterator::Subdirectories);dirs<<m_projectRoot+"/assets";while(dit.hasNext())dirs<<dit.next();for(const auto&d:dirs)if(QFileInfo::exists(d))m_watcher->addPath(d);QDirIterator fit(m_projectRoot+"/assets",QDir::Files,QDirIterator::Subdirectories);QStringList files;while(fit.hasNext())files<<fit.next();if(!files.isEmpty())m_watcher->addPaths(files);}
void MainWindow::onWatchedPathChanged(const QString&p){Q_UNUSED(p);if(m_projectRoot.isEmpty())return;m_assetDb->refresh();m_profiler->refresh();loadProjectTree(m_projectRoot);updateFileWatchers();statusBar()->showMessage("Asset change detected; reimport scheduled",2500);QTimer::singleShot(300,this,[this]{if(m_projectRoot.isEmpty())return;auto r=AssetCompiler::compileProject(m_projectRoot);if(r.ok){appendOutput(QString("Auto-reimport: %1 textures, %2 meshes, %3 sounds\n").arg(r.textures).arg(r.meshes).arg(r.sounds));if(m_liveReload&&!m_liveReloadPending){m_liveReloadPending=true;QTimer::singleShot(500,this,[this]{m_liveReloadPending=false;buildAndRun();});}}else appendOutput("Auto-reimport failed: "+r.error+"\n");});}
void MainWindow::configureProject(){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"Project Settings","Open a project first.");return;}QDialog d(this);d.setWindowTitle("Project Settings");QFormLayout f(&d);QLineEdit host(m_ps2Host),pcsx(m_pcsx2Path);QSpinBox autos;autos.setRange(15,3600);autos.setValue(m_autosaveSeconds);QPushButton browse("Browse...");QWidget row;QHBoxLayout rh(&row);rh.setContentsMargins(0,0,0,0);rh.addWidget(&pcsx);rh.addWidget(&browse);connect(&browse,&QPushButton::clicked,&d,[&]{auto x=QFileDialog::getOpenFileName(&d,"PCSX2 executable");if(!x.isEmpty())pcsx.setText(x);});f.addRow("Real PS2 IP / host",&host);f.addRow("PCSX2 executable",&row);f.addRow("Autosave interval (sec)",&autos);QDialogButtonBox box(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);f.addRow(&box);connect(&box,&QDialogButtonBox::accepted,&d,&QDialog::accept);connect(&box,&QDialogButtonBox::rejected,&d,&QDialog::reject);if(d.exec()!=QDialog::Accepted)return;m_ps2Host=host.text().trimmed();m_pcsx2Path=pcsx.text().trimmed();m_autosaveSeconds=autos.value();{QSettings st("PS2Studio","PS2Studio");st.setValue("ps2Host",m_ps2Host);st.setValue("pcsx2Path",m_pcsx2Path);}m_autosaveTimer->setInterval(m_autosaveSeconds*1000);writeProjectConfig();updateEnvironmentPanel();}
void MainWindow::navigateBuildError(){auto line=m_buildOutput->textCursor().block().text();QString file;int ln=0,col=1;QRegularExpression gcc(R"(([A-Za-z]:)?([^:\n]+\.(?:c|cc|cpp|cxx|h|hpp)):(\d+)(?::(\d+))?)");auto gm=gcc.match(line);if(gm.hasMatch()){file=gm.captured(1)+gm.captured(2);ln=gm.captured(3).toInt();if(!gm.captured(4).isEmpty())col=gm.captured(4).toInt();}else{QRegularExpression msvc(R"(([^\n\r]+\.(?:c|cc|cpp|cxx|h|hpp))\((\d+)(?:,(\d+))?\))");auto mm=msvc.match(line);if(mm.hasMatch()){file=mm.captured(1).trimmed();ln=mm.captured(2).toInt();if(!mm.captured(3).isEmpty())col=mm.captured(3).toInt();}}if(file.isEmpty()||ln<=0)return;if(QDir::isRelativePath(file))file=QDir(m_projectRoot).filePath(file);if(!QFileInfo::exists(file))return;openFile(file);if(auto*ed=currentEditor())ed->gotoLine(ln,col);m_workspaceTabs->setCurrentWidget(m_editorTabs);}

bool MainWindow::eventFilter(QObject*watched,QEvent*event){if(watched==m_buildOutput&&event->type()==QEvent::MouseButtonDblClick){navigateBuildError();return true;}return QMainWindow::eventFilter(watched,event);}


CodeEditor* MainWindow::currentEditor() const{return dynamic_cast<CodeEditor*>(m_editorTabs?m_editorTabs->currentWidget():nullptr);}
void MainWindow::updateEditorTab(CodeEditor*ed){if(!ed)return;int i=m_editorTabs->indexOf(ed);if(i<0)return;QString n=ed->filePath().isEmpty()?"Untitled":QFileInfo(ed->filePath()).fileName();if(ed->document()->isModified())n+=" *";m_editorTabs->setTabText(i,n);m_editorTabs->setTabToolTip(i,ed->filePath());}
bool MainWindow::saveEditor(CodeEditor*ed){if(!ed)return true;if(ed->filePath().isEmpty()){QString p=QFileDialog::getSaveFileName(this,"Save Source",m_projectRoot+"/src/main.cpp");if(p.isEmpty())return false;QString e;if(!ed->saveFileAs(p,&e)){QMessageBox::warning(this,"Save",e);return false;}}else{QString e;if(!ed->saveFile(&e)){QMessageBox::warning(this,"Save",e);return false;}}updateEditorTab(ed);return true;}
bool MainWindow::saveAllEditors(){for(int i=0;i<m_editorTabs->count();++i){auto*ed=dynamic_cast<CodeEditor*>(m_editorTabs->widget(i));if(ed&&ed->document()->isModified()&&!saveEditor(ed))return false;}return true;}

bool MainWindow::closeEditorTab(int index){auto*ed=dynamic_cast<CodeEditor*>(m_editorTabs->widget(index));if(!ed){m_editorTabs->removeTab(index);return true;}if(ed->document()->isModified()){auto r=QMessageBox::question(this,"Unsaved Source",QString("Save changes to %1?").arg(QFileInfo(ed->filePath()).fileName()),QMessageBox::Save|QMessageBox::Discard|QMessageBox::Cancel);if(r==QMessageBox::Cancel)return false;if(r==QMessageBox::Save&&!saveEditor(ed))return false;}if(m_clangd&&m_clangd->isRunning())m_clangd->closeDocument(ed->filePath());m_editorTabs->removeTab(index);ed->deleteLater();return true;}
void MainWindow::createCodeFile(const QString&subdir,const QString&suffix){if(m_projectRoot.isEmpty()){QMessageBox::information(this,"New Source","Open a project first.");return;}bool ok=false;QString name=QInputDialog::getText(this,"New Source","File name:",QLineEdit::Normal,suffix==".h"?"Component.h":"Component.cpp",&ok).trimmed();if(!ok||name.isEmpty())return;if(!name.endsWith(suffix,Qt::CaseInsensitive)&&!name.contains('.'))name+=suffix;QString dir=m_projectRoot+"/"+subdir;QDir().mkpath(dir);QString path=QDir(dir).filePath(name);if(QFileInfo::exists(path)){QMessageBox::warning(this,"New Source","File already exists.");return;}QFile f(path);if(!f.open(QIODevice::WriteOnly|QIODevice::Text)){QMessageBox::warning(this,"New Source",f.errorString());return;}if(suffix==".h")f.write("#pragma once\n\n");else f.write("#include <tamtypes.h>\n\n");f.close();loadProjectTree(m_projectRoot);openFile(path);}
void MainWindow::newSourceFile(){createCodeFile("src",".cpp");}
void MainWindow::newHeaderFile(){createCodeFile("include",".h");}
void MainWindow::newComponent(){
    if(m_projectRoot.isEmpty()){QMessageBox::information(this,"New Component","Open a project first.");return;}
    bool ok=false;QString name=QInputDialog::getText(this,"New Gameplay Component","Component name:",QLineEdit::Normal,"PlayerController",&ok).trimmed();if(!ok||name.isEmpty())return;
    QString sym=name;sym.replace(QRegularExpression("[^A-Za-z0-9_]"),"_");if(sym.isEmpty())return;if(sym[0].isDigit())sym.prepend("C_");QString file=sym+".cpp";QString path=m_projectRoot+"/scripts/"+file;
    if(QFileInfo::exists(path)){QMessageBox::warning(this,"New Component","That component already exists.");openFile(path);return;}
    QFile f(path);if(!f.open(QIODevice::WriteOnly|QIODevice::Text)){QMessageBox::warning(this,"New Component",f.errorString());return;}f.write(ps2ComponentExample(sym).toUtf8());f.close();
    if(auto*o=m_scene->objectById(m_selectedObjectId)){o->script=file;m_scene->notifyChanged();m_inspector->setObjectId(o->id);}loadProjectTree(m_projectRoot);openFile(path);
}
void MainWindow::findReferences(){
    auto* ed=currentEditor();if(!ed)return;QString clangd=findExecutable({"clangd","clangd.exe"});if(clangd.isEmpty())return;
    if(!m_clangd->isRunning()&&!m_clangd->start(clangd,m_projectRoot))return;
    m_clangd->changeDocument(ed->filePath(),ed->toPlainText());auto c=ed->textCursor();
    m_clangd->requestReferences(ed->filePath(),c.blockNumber(),c.positionInBlock(),[this](QList<QPair<QString,int>> refs){
        if(refs.isEmpty()){statusBar()->showMessage("clangd: no references",2500);return;}
        QDialog d(this);d.setWindowTitle("References");auto*l=new QVBoxLayout(&d);auto*list=new QListWidget;for(const auto&r:refs){auto*i=new QListWidgetItem(QString("%1:%2").arg(r.first).arg(r.second));i->setData(Qt::UserRole,r.first);i->setData(Qt::UserRole+1,r.second);list->addItem(i);}l->addWidget(list);connect(list,&QListWidget::itemDoubleClicked,&d,[this,&d](QListWidgetItem*i){openFile(i->data(Qt::UserRole).toString());if(auto*e=currentEditor())e->gotoLine(i->data(Qt::UserRole+1).toInt());d.accept();});d.resize(760,420);d.exec();
    });
}
void MainWindow::renameSymbol(){
    auto*ed=currentEditor();if(!ed)return;bool ok=false;QString n=QInputDialog::getText(this,"Rename Symbol","New name:",QLineEdit::Normal,{},&ok).trimmed();if(!ok||n.isEmpty())return;QString clangd=findExecutable({"clangd","clangd.exe"});if(clangd.isEmpty())return;if(!m_clangd->isRunning()&&!m_clangd->start(clangd,m_projectRoot))return;m_clangd->changeDocument(ed->filePath(),ed->toPlainText());auto c=ed->textCursor();m_clangd->requestRename(ed->filePath(),c.blockNumber(),c.positionInBlock(),n,[this](QJsonObject edit){auto changes=edit.value("changes").toObject();int files=0,edits=0;for(auto it=changes.begin();it!=changes.end();++it){QString file=QUrl(it.key()).toLocalFile();QFile f(file);if(!f.open(QIODevice::ReadOnly|QIODevice::Text))continue;QString text=QString::fromUtf8(f.readAll());f.close();auto arr=it.value().toArray();QVector<QPair<int,QJsonObject>> replacements;for(const auto&v:arr){auto o=v.toObject();auto st=o.value("range").toObject().value("start").toObject();int line=st.value("line").toInt();int ch=st.value("character").toInt();QTextDocument doc(text);QTextBlock b=doc.findBlockByLineNumber(line);replacements.push_back({b.position()+ch,o});}std::sort(replacements.begin(),replacements.end(),[](auto&a,auto&b){return a.first>b.first;});for(const auto&r:replacements){auto range=r.second.value("range").toObject();auto st=range.value("start").toObject();auto en=range.value("end").toObject();QTextDocument doc(text);int a=doc.findBlockByLineNumber(st.value("line").toInt()).position()+st.value("character").toInt();int b=doc.findBlockByLineNumber(en.value("line").toInt()).position()+en.value("character").toInt();text.replace(a,b-a,r.second.value("newText").toString());++edits;}QSaveFile out(file);if(out.open(QIODevice::WriteOnly|QIODevice::Text)){out.write(text.toUtf8());out.commit();++files;}}statusBar()->showMessage(QString("Renamed symbol: %1 edits in %2 files").arg(edits).arg(files),4000);loadProjectTree(m_projectRoot);});
}
void MainWindow::showHover(){
    auto*ed=currentEditor();if(!ed)return;QString clangd=findExecutable({"clangd","clangd.exe"});if(clangd.isEmpty())return;if(!m_clangd->isRunning()&&!m_clangd->start(clangd,m_projectRoot))return;m_clangd->changeDocument(ed->filePath(),ed->toPlainText());auto c=ed->textCursor();m_clangd->requestHover(ed->filePath(),c.blockNumber(),c.positionInBlock(),[this](QString text){if(text.isEmpty())text="No type/hover information.";QMessageBox::information(this,"clangd",text.left(4000));});
}
void MainWindow::requestSmartCompletion(){
    auto*ed=currentEditor();if(!ed)return;QString clangd=findExecutable({"clangd","clangd.exe"});if(clangd.isEmpty())return;if(!m_clangd->isRunning()&&!m_clangd->start(clangd,m_projectRoot))return;m_clangd->changeDocument(ed->filePath(),ed->toPlainText());auto c=ed->textCursor();m_clangd->requestCompletion(ed->filePath(),c.blockNumber(),c.positionInBlock(),[ed](QStringList items){if(!items.isEmpty())ed->setCompletionItems(items);});
}

void MainWindow::findInEditor(){auto*ed=currentEditor();if(!ed)return;bool ok=false;QString q=QInputDialog::getText(this,"Find","Text:",QLineEdit::Normal,{},&ok);if(ok&&!q.isEmpty()&&!ed->find(q)){QTextCursor c=ed->textCursor();c.movePosition(QTextCursor::Start);ed->setTextCursor(c);ed->find(q);}}
void MainWindow::replaceInEditor(){auto*ed=currentEditor();if(!ed)return;QDialog d(this);d.setWindowTitle("Replace");QFormLayout l(&d);QLineEdit find,rep;l.addRow("Find",&find);l.addRow("Replace with",&rep);QDialogButtonBox box(QDialogButtonBox::Ok|QDialogButtonBox::Cancel);l.addRow(&box);connect(&box,&QDialogButtonBox::accepted,&d,&QDialog::accept);connect(&box,&QDialogButtonBox::rejected,&d,&QDialog::reject);if(d.exec()!=QDialog::Accepted||find.text().isEmpty())return;QString t=ed->toPlainText();t.replace(find.text(),rep.text());ed->setPlainText(t);ed->document()->setModified(true);}
void MainWindow::gotoLine(){auto*ed=currentEditor();if(!ed)return;bool ok=false;int n=QInputDialog::getInt(this,"Go to Line","Line:",ed->currentLine(),1,qMax(1,ed->blockCount()),1,&ok);if(ok)ed->gotoLine(n);}
void MainWindow::toggleBreakpoint(){auto*ed=currentEditor();if(!ed)return;int line=ed->currentLine();bool enabled=ed->toggleBreakpoint(line);if(m_debugger)m_debugger->toggleBreakpoint(ed->filePath(),line,enabled);statusBar()->showMessage(QString("Breakpoint %1 at %2:%3").arg(enabled?"set":"cleared").arg(QFileInfo(ed->filePath()).fileName()).arg(line),2000);}
QString MainWindow::resolveMake() const{return findExecutable({"make","mingw32-make"});}
QString MainWindow::resolvePCSX2() const{if(!m_pcsx2Path.isEmpty()&&QFileInfo::exists(m_pcsx2Path))return m_pcsx2Path;QString p=findExecutable({"pcsx2-qt","pcsx2","pcsx2-qtx64-avx2"});if(!p.isEmpty())return p;
#ifdef Q_OS_WIN
    QStringList roots={"C:/Program Files/PCSX2","C:/Program Files/PCSX2 Nightly",qEnvironmentVariable("LOCALAPPDATA")+"/Programs/PCSX2"};for(const auto&r:roots){if(r.isEmpty()||!QFileInfo::exists(r))continue;QDirIterator it(r,{"pcsx2-qt.exe","pcsx2.exe"},QDir::Files,QDirIterator::Subdirectories);if(it.hasNext())return it.next();}
#endif
    return{};}
QProcessEnvironment MainWindow::buildEnvironment() const{auto pe=QProcessEnvironment::systemEnvironment();QString ps2dev=pe.value("PS2DEV");if(ps2dev.isEmpty()&&QFileInfo::exists("C:/ps2dev"))ps2dev="C:/ps2dev";QString sdk=pe.value("PS2SDK");if(sdk.isEmpty()&&!ps2dev.isEmpty())sdk=ps2dev+"/ps2sdk";QString gs=pe.value("GSKIT");if(gs.isEmpty()&&!ps2dev.isEmpty())gs=ps2dev+"/gsKit";if(!ps2dev.isEmpty())pe.insert("PS2DEV",ps2dev);if(!sdk.isEmpty())pe.insert("PS2SDK",sdk);if(!gs.isEmpty())pe.insert("GSKIT",gs);QStringList add;if(!ps2dev.isEmpty())add<<ps2dev+"/bin"<<ps2dev+"/ee/bin"<<ps2dev+"/iop/bin"<<ps2dev+"/dvp/bin";if(!sdk.isEmpty())add<<sdk+"/bin";
#ifdef Q_OS_WIN
    if(QFileInfo::exists("C:/msys64/usr/bin"))add<<"C:/msys64/usr/bin";
#endif
    QString path=pe.value("PATH");for(auto it=add.crbegin();it!=add.crend();++it)if(!path.contains(*it,Qt::CaseInsensitive))path=*it+QDir::listSeparator()+path;pe.insert("PATH",path);return pe;}
bool MainWindow::ensureIopSkeleton(QString*error){if(m_projectRoot.isEmpty())return false;QString dir=m_projectRoot+"/iop";QDir().mkpath(dir);auto write=[&](const QString&name,const QString&text){QString p=dir+"/"+name;if(QFileInfo::exists(p))return true;QFile f(p);if(!f.open(QIODevice::WriteOnly|QIODevice::Text)){if(error)*error=f.errorString();return false;}f.write(text.toUtf8());return true;};
    if(!write("Makefile",R"IOP(IOP_BIN = ps2studio_sample.irx
IOP_OBJS = module_main.o module_exports.o imports.o exports.o
all: $(IOP_BIN)
clean:
	rm -f -r $(IOP_OBJS) $(IOP_BIN)
include $(PS2SDK)/Defs.make
include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.iopglobal
)IOP"))return false;
    if(!write("irx_imports.h",R"IOP(#pragma once
#include "irx.h"
#include "loadcore.h"
#include "stdio.h"
)IOP"))return false;
    if(!write("module.h","#pragma once\nextern void ps2studio_iop_hello(void);\n"))return false;
    if(!write("module_main.c",R"IOP(#include "irx_imports.h"
#include "module.h"
IRX_ID("PS2 Studio IOP", 1, 0);
extern struct irx_export_table _exp_ps2studio;
int _start(int argc, char *argv[]){(void)argc;(void)argv;if(RegisterLibraryEntries(&_exp_ps2studio)!=0)return MODULE_NO_RESIDENT_END;ps2studio_iop_hello();return MODULE_RESIDENT_END;}
)IOP"))return false;
    if(!write("module_exports.c","#include \"irx_imports.h\"\n#include \"module.h\"\nvoid ps2studio_iop_hello(void){printf(\"PS2 Studio IOP module loaded\\n\");}\n"))return false;
    if(!write("imports.lst","loadcore_IMPORTS_start\nI_RegisterLibraryEntries\nloadcore_IMPORTS_end\n\nstdio_IMPORTS_start\nI_printf\nstdio_IMPORTS_end\n"))return false;
    if(!write("exports.tab","DECLARE_EXPORT_TABLE(ps2studio, 1, 0)\n        DECLARE_EXPORT(_start)\n        DECLARE_EXPORT(_retonly)\n        DECLARE_EXPORT(_retonly)\n        DECLARE_EXPORT(_retonly)\n        DECLARE_EXPORT(ps2studio_iop_hello)\nEND_EXPORT_TABLE\nvoid _retonly() {}\n"))return false;return true;}
void MainWindow::prepareRuntimeSupportFiles(){auto pe=buildEnvironment();QString sdk=pe.value("PS2SDK");if(sdk.isEmpty())return;QString dst=m_projectRoot+"/audsrv.irx";if(QFileInfo::exists(dst))return;QDirIterator it(sdk,{"audsrv.irx"},QDir::Files,QDirIterator::Subdirectories);if(it.hasNext())QFile::copy(it.next(),dst);}
void MainWindow::regenerateRuntimeTemplates(){if(m_projectRoot.isEmpty())return;if(QMessageBox::question(this,"Regenerate Runtime","Replace runtime/PS2SceneRuntime.*, runtime/vu1_transform.vsm and Makefile with the current PS2 Studio templates? Your src/main.cpp is preserved.")!=QMessageBox::Yes)return;auto write=[&](QString p,QString t){QFile f(m_projectRoot+"/"+p);if(f.open(QIODevice::WriteOnly|QIODevice::Truncate|QIODevice::Text))f.write(t.toUtf8());};QFile meta(m_projectRoot+"/ps2studio.json");QString name=QFileInfo(m_projectRoot).fileName();if(meta.open(QIODevice::ReadOnly)){auto o=QJsonDocument::fromJson(meta.readAll()).object();name=o.value("name").toString(name);}write("runtime/PS2SceneRuntime.h",ps2RuntimeHeader());write("runtime/PS2SceneRuntime.cpp",ps2RuntimeSource());write("runtime/vu1_transform.vsm",ps2VuProgram());write("Makefile",ps2Makefile(name));ensureIopSkeleton();loadProjectTree(m_projectRoot);QMessageBox::information(this,"Runtime","Runtime templates regenerated.");}

void MainWindow::openDependencyManager(){DependencyManagerDialog d(this);d.exec();refreshEnvironment();}
