#include "ProfilerWidget.h"
#include "SceneDocument.h"
#include <QtWidgets>
#include <QDirIterator>
#include <QImage>
#include <QRegularExpression>
ProfilerWidget::ProfilerWidget(QWidget*p):QWidget(p){auto*l=new QVBoxLayout(this);m_text=new QLabel;m_text->setTextInteractionFlags(Qt::TextSelectableByMouse);m_text->setAlignment(Qt::AlignTop|Qt::AlignLeft);l->addWidget(m_text);auto*b=new QPushButton("Refresh Estimates");l->addWidget(b);connect(b,&QPushButton::clicked,this,&ProfilerWidget::refresh);}
void ProfilerWidget::setProjectRoot(const QString&r){m_root=r;refresh();}void ProfilerWidget::setDocument(SceneDocument*d){m_doc=d;refresh();}
void ProfilerWidget::setFrameTime(float ms){m_frameMs=ms;refresh();}
void ProfilerWidget::ingestRuntimeOutput(const QString& text){
    static QRegularExpression re(R"(\[PS2StudioProfiler\]\s+frame=(\d+)\s+entities=(\d+)\s+drawCalls=(\d+)\s+triangles=(\d+)\s+collisions=(\d+)\s+audio=(\d+)(?:\s+physicsPairs=(\d+)\s+skinVertices=(\d+)\s+vifPackets=(\d+)\s+vuDispatches=(\d+))?)");
    auto it=re.globalMatch(text);bool changed=false;while(it.hasNext()){auto m=it.next();m_runtimeFrame=m.captured(1).toUInt();m_runtimeEntities=m.captured(2).toUInt();m_runtimeDrawCalls=m.captured(3).toUInt();m_runtimeTriangles=m.captured(4).toUInt();m_runtimeCollisions=m.captured(5).toUInt();m_runtimeAudioVoices=m.captured(6).toUInt();if(!m.captured(7).isEmpty()){m_runtimePhysicsPairs=m.captured(7).toUInt();m_runtimeSkinVertices=m.captured(8).toUInt();m_runtimeVifPackets=m.captured(9).toUInt();m_runtimeVuDispatches=m.captured(10).toUInt();}m_hasRuntimeStats=true;changed=true;}if(changed)refresh();
}
void ProfilerWidget::refresh(){qint64 tex=0,audio=0,models=0;int tc=0,mc=0,ac=0;if(!m_root.isEmpty()){QDirIterator it(m_root+"/assets/textures",QDir::Files,QDirIterator::Subdirectories);while(it.hasNext()){QImage im(it.next());if(!im.isNull()){tex+=qint64(im.width())*im.height()*4;tc++;}}QDirIterator mi(m_root+"/assets/models",QDir::Files,QDirIterator::Subdirectories);while(mi.hasNext()){QFileInfo f(mi.next());models+=f.size();mc++;}QDirIterator ai(m_root+"/assets/audio",QDir::Files,QDirIterator::Subdirectories);while(ai.hasNext()){QFileInfo f(ai.next());audio+=f.size();ac++;}}
    int entities=m_doc?m_doc->objects().size():0;auto kb=[](qint64 n){return QString::number(n/1024.0,'f',1)+" KiB";};QString rt=m_hasRuntimeStats?QString("\n\nRuntime counters (PCSX2/console log):\nFrame: %1\nEntities: %2\nDraw calls: %3\nTriangles: %4\nCollisions: %5\nAudio voices started: %6\nPhysics pairs: %7\nSkinned vertices: %8\nVIF packets: %9\nVU1 dispatches: %10").arg(m_runtimeFrame).arg(m_runtimeEntities).arg(m_runtimeDrawCalls).arg(m_runtimeTriangles).arg(m_runtimeCollisions).arg(m_runtimeAudioVoices).arg(m_runtimePhysicsPairs).arg(m_runtimeSkinVertices).arg(m_runtimeVifPackets).arg(m_runtimeVuDispatches):QString("\n\nRuntime counters: waiting for [PS2StudioProfiler] output from the running ELF.");m_text->setText(QString("Frame time (editor sim): %9 ms  (%10 FPS)\nScene entities: %1\nTextures: %2 (%3)\nEstimated texture RAM before GS swizzle: %4\nModels: %5 (%6 source bytes)\nAudio: %7 (%8 source bytes)\n\nPS2 GS VRAM is 4 MiB. Texture estimate is conservative and does not include framebuffer/Z-buffer allocations.\nVU1 workspace and EE heap are runtime-dependent.%11").arg(entities).arg(tc).arg(kb(tex)).arg(kb(tex)).arg(mc).arg(kb(models)).arg(ac).arg(kb(audio)).arg(QString::number(m_frameMs,'f',2)).arg(m_frameMs>0.0f?QString::number(1000.0f/m_frameMs,'f',1):QString("--")).arg(rt));}
