#include "SampleProjectGenerator.h"
#include <QtCore>
#include <QtMath>
#include <cstring>
namespace SampleProjectGenerator{
static bool wr(const QString&p,const QByteArray&d){QFile f(p);QDir().mkpath(QFileInfo(p).absolutePath());return f.open(QIODevice::WriteOnly|QIODevice::Truncate)&&f.write(d)==d.size();}
static QByteArray checkerBmp(){const int w=64,h=64,row=w*3,size=54+row*h;QByteArray b(size,0);auto u16=[&](int o,quint16 v){b[o]=char(v);b[o+1]=char(v>>8);};auto u32=[&](int o,quint32 v){for(int i=0;i<4;i++)b[o+i]=char(v>>(i*8));};b[0]='B';b[1]='M';u32(2,size);u32(10,54);u32(14,40);u32(18,w);u32(22,h);u16(26,1);u16(28,24);u32(34,row*h);for(int y=0;y<h;y++)for(int x=0;x<w;x++){bool c=((x/8)+(y/8))%2;int o=54+y*row+x*3;b[o]=char(c?40:220);b[o+1]=char(c?120:80);b[o+2]=char(c?240:60);}return b;}
static QByteArray beepWav(){const int rate=22050,samples=rate/5,data=samples*2;QByteArray b(44+data,0);auto put=[&](int o,const char*s,int n){memcpy(b.data()+o,s,n);};auto u16=[&](int o,quint16 v){b[o]=char(v);b[o+1]=char(v>>8);};auto u32=[&](int o,quint32 v){for(int i=0;i<4;i++)b[o+i]=char(v>>(i*8));};put(0,"RIFF",4);u32(4,36+data);put(8,"WAVEfmt ",8);u32(16,16);u16(20,1);u16(22,1);u32(24,rate);u32(28,rate*2);u16(32,2);u16(34,16);put(36,"data",4);u32(40,data);for(int i=0;i<samples;i++){double t=double(i)/rate;short v=short(10000.0*qSin(2.0*3.141592653589793*440.0*t));b[44+i*2]=char(v);b[45+i*2]=char(v>>8);}return b;}
static QByteArray cubeObj(){return QByteArray("v -1 -1 -1\nv 1 -1 -1\nv 1 1 -1\nv -1 1 -1\nv -1 -1 1\nv 1 -1 1\nv 1 1 1\nv -1 1 1\nvt 0 0\nvt 1 0\nvt 1 1\nvt 0 1\nf 1/1 2/2 3/3\nf 1/1 3/3 4/4\nf 5/1 8/4 7/3\nf 5/1 7/3 6/2\nf 1/1 5/2 6/3\nf 1/1 6/3 2/4\nf 2/1 6/2 7/3\nf 2/1 7/3 3/4\nf 3/1 7/2 8/3\nf 3/1 8/3 4/4\nf 5/1 1/2 4/3\nf 5/1 4/3 8/4\n");}
static QJsonObject obj(QString id,QString name,QString type,QJsonArray pos={0,0,0}){return QJsonObject{{"id",id},{"name",name},{"type",type},{"tag",""},{"position",pos},{"rotation",QJsonArray{0,0,0}},{"scale",QJsonArray{1,1,1}},{"velocity",QJsonArray{0,0,0}},{"asset",""},{"materialTexture",""},{"animationAsset",""},{"script",""},{"prefabSource",""},{"uiText",""},{"nextScene",""},{"colliderEnabled",false},{"colliderSize",QJsonArray{32,32,1}},{"trigger",false},{"rigidBody",false},{"mass",1.0},{"particleEmitter",false},{"particleCount",32},{"particleLife",1.0}};}
static bool scene(const QString&p,const QJsonArray&objects){return wr(p,QJsonDocument(QJsonObject{{"format","PS2StudioScene"},{"version",2},{"objects",objects}}).toJson(QJsonDocument::Indented));}
bool create(const QString& root,const QString& kind,QString*e){if(root.isEmpty()){if(e)*e="No project root";return false;}QDir().mkpath(root+"/samples");QDir().mkpath(root+"/assets/textures");QDir().mkpath(root+"/assets/models");QDir().mkpath(root+"/assets/audio");wr(root+"/assets/textures/sample_checker.bmp",checkerBmp());wr(root+"/assets/models/sample_cube.obj",cubeObj());wr(root+"/assets/audio/sample_beep.wav",beepWav());QJsonArray a;auto cam=obj("sample-camera","Main Camera","Camera",{0,0,-6});a.append(cam);if(kind=="2D"||kind=="Validation"){auto s=obj("sample-sprite","Player Sprite","Sprite",{160,120,0});s["asset"]="sample_checker.bmp";s["tag"]="Player";s["colliderEnabled"]=true;s["rigidBody"]=true;s["animationAsset"]="sample_beep.wav";a.append(s);}if(kind=="3D"||kind=="Validation"){auto m=obj("sample-mesh","Textured Cube","Mesh",{0,0,5});m["asset"]="sample_cube.obj";m["materialTexture"]="sample_checker.bmp";m["colliderEnabled"]=true;a.append(m);auto l=obj("sample-light","Key Light","Light",{2,4,0});a.append(l);}if(kind=="Validation"){auto t=obj("sample-text","Validation UI","Text",{20,30,0});t["uiText"]="PS2 Studio Validation";a.append(t);auto p=obj("sample-particles","Particles","Empty",{320,224,0});p["particleEmitter"]=true;p["particleCount"]=24;p["particleLife"]=1.5;a.append(p);}QString sceneName=kind+"Sample.ps2scene";if(!scene(root+"/scenes/"+sceneName,a)){if(e)*e="Could not write sample scene";return false;}QString md=QString("# %1 Sample\n\nScene: `scenes/%2`\n\nAssets are self-contained: checker BMP, UV cube OBJ, and 16-bit PCM WAV.\n\nValidate Game View first, then PCSX2, then real hardware.\n").arg(kind,sceneName);wr(root+"/samples/"+kind+"-README.md",md.toUtf8());QJsonObject o{{"kind",kind},{"createdBy","PS2 Studio 0.15"},{"scene",sceneName},{"purpose",kind=="Validation"?"end-to-end integration":"example"}};wr(root+"/samples/"+kind+"-sample.json",QJsonDocument(o).toJson(QJsonDocument::Indented));return true;}
}
