#include "ValidationCenterDialog.h"
#include <QtWidgets>
#include <QJsonDocument>
#include <QJsonObject>
#include <QStandardPaths>
#include <QProcessEnvironment>
#include <QDirIterator>

static QString vcFind(const QStringList& names){for(const auto&n:names){auto p=QStandardPaths::findExecutable(n);if(!p.isEmpty())return p;}QString ps2=qEnvironmentVariable("PS2DEV");if(ps2.isEmpty()&&QFileInfo::exists("C:/ps2dev"))ps2="C:/ps2dev";QStringList dirs;if(!ps2.isEmpty())dirs<<ps2+"/ee/bin"<<ps2+"/iop/bin"<<ps2+"/dvp/bin"<<ps2+"/ps2sdk/bin";
#ifdef Q_OS_WIN
 dirs<<"C:/msys64/usr/bin"<<"C:/Program Files/PCSX2";QString la=qEnvironmentVariable("LOCALAPPDATA");if(!la.isEmpty())dirs<<la+"/Microsoft/WinGet/Links"<<la+"/Programs/PCSX2";
#endif
 for(const auto&d:dirs)for(auto n:names){
#ifdef Q_OS_WIN
  if(!n.endsWith(".exe",Qt::CaseInsensitive))n+=".exe";
#endif
  QString p=QDir(d).filePath(n);if(QFileInfo::exists(p))return p;}return{};}

ValidationCenterDialog::ValidationCenterDialog(const QString&r,const QString&p,const QString&h,QWidget*parent):QDialog(parent),m_root(r),m_pcsx2(p),m_host(h){setWindowTitle("PS2 Studio Validation Center");resize(900,600);auto*l=new QVBoxLayout(this);m_summary=new QLabel;l->addWidget(m_summary);m_tree=new QTreeWidget;m_tree->setHeaderLabels({"Check","Status","Details"});m_tree->header()->setSectionResizeMode(2,QHeaderView::Stretch);l->addWidget(m_tree,1);auto*row=new QHBoxLayout;auto*run=new QPushButton("Run Checks");auto*save=new QPushButton("Export Report");auto*close=new QPushButton("Close");row->addWidget(run);row->addWidget(save);row->addStretch();row->addWidget(close);l->addLayout(row);connect(run,&QPushButton::clicked,this,&ValidationCenterDialog::runChecks);connect(save,&QPushButton::clicked,this,&ValidationCenterDialog::exportReport);connect(close,&QPushButton::clicked,this,&QDialog::accept);runChecks();}
void ValidationCenterDialog::runChecks(){m_tree->clear();int pass=0,total=0;auto add=[&](QString n,bool ok,QString d){++total;if(ok)++pass;auto*i=new QTreeWidgetItem({n,ok?"PASS":"NEEDS ATTENTION",d});m_tree->addTopLevelItem(i);};auto env=QProcessEnvironment::systemEnvironment();auto exe=[](QStringList n){return !vcFind(n).isEmpty();};add("Project open",!m_root.isEmpty()&&QFileInfo::exists(m_root),m_root);add("Project metadata",QFileInfo::exists(m_root+"/ps2studio.json"),"ps2studio.json");add("Main source",QFileInfo::exists(m_root+"/src/main.cpp"),"src/main.cpp");add("Runtime",QFileInfo::exists(m_root+"/runtime/PS2SceneRuntime.cpp"),"runtime/PS2SceneRuntime.cpp");add("Scene",QDir(m_root+"/scenes").entryList({"*.ps2scene"},QDir::Files).size()>0,"At least one .ps2scene");QString ps2=env.value("PS2DEV");if(ps2.isEmpty()&&QFileInfo::exists("C:/ps2dev"))ps2="C:/ps2dev";add("PS2DEV",!ps2.isEmpty(),ps2);add("PS2SDK",QFileInfo::exists(ps2+"/ps2sdk"),ps2+"/ps2sdk");add("gsKit",QFileInfo::exists(ps2+"/gsKit"),ps2+"/gsKit");add("GNU make",exe({"make","mingw32-make"}),vcFind({"make","mingw32-make"}));add("EE compiler",exe({"mips64r5900el-ps2-elf-g++"}),vcFind({"mips64r5900el-ps2-elf-g++"}));add("IOP compiler",exe({"mipsel-none-elf-gcc"}),vcFind({"mipsel-none-elf-gcc"}));add("DVP assembler",exe({"dvp-as"}),vcFind({"dvp-as"}));add("ps2client",exe({"ps2client"}),vcFind({"ps2client"}));QString pc=QFileInfo::exists(m_pcsx2)?m_pcsx2:vcFind({"pcsx2-qt","pcsx2"});add("PCSX2",!pc.isEmpty(),pc);add("ISO authoring",exe({"xorriso","mkisofs","genisoimage","oscdimg"}),"Optional disc workflow");add("Real PS2 host configured",!m_host.trimmed().isEmpty(),m_host);m_summary->setText(QString("Automated checks: %1/%2 passed. Hardware boot, controller/audio correctness, and burned-disc boot remain manual verification steps.").arg(pass).arg(total));}
void ValidationCenterDialog::exportReport(){auto p=QFileDialog::getSaveFileName(this,"Export Validation Report",m_root+"/validation-report.json","JSON (*.json)");if(p.isEmpty())return;QJsonArray a;for(int i=0;i<m_tree->topLevelItemCount();++i){auto*x=m_tree->topLevelItem(i);a.append(QJsonObject{{"check",x->text(0)},{"status",x->text(1)},{"details",x->text(2)}});}QJsonObject root{{"project",m_root},{"checks",a},{"manualVerification",QJsonArray{"PCSX2 gameplay","real PS2 deployment","controller/audio behavior","burned disc read-back","real console boot"}}};QFile f(p);if(f.open(QIODevice::WriteOnly|QIODevice::Truncate))f.write(QJsonDocument(root).toJson(QJsonDocument::Indented));}
